/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

/* Global variables */
StradaValue *g_var_types = NULL;
StradaValue *g_functions = NULL;
StradaValue *g_eval_count = NULL;
StradaValue *g_tmpdir = NULL;
StradaValue *g_debug = NULL;

void repl_debug(StradaValue* msg);
StradaValue* is_function_def(StradaValue* input);
StradaValue* is_package_decl(StradaValue* input);
StradaValue* is_import(StradaValue* input);
StradaValue* get_var_decl_type(StradaValue* input, StradaValue* sigil);
StradaValue* generate_eval_source(StradaValue* input, StradaValue* state);
void register_variables(StradaValue* input);
StradaValue* eval_input(StradaValue* input, StradaValue* state);
StradaValue* format_value(StradaValue* val);
StradaValue* is_balanced(StradaValue* input);
void print_help(void);
StradaValue* read_line(void);
int main(int _argc, char **_argv);

void repl_debug(StradaValue* msg) {
if ((strada_to_num(g_debug) == 1.0)) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("[DEBUG] "); StradaValue *__concat_res = strada_concat_sv(__concat_l, msg); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
}


StradaValue* is_function_def(StradaValue* input) {
if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "^\\s*(private\\s+)?func\\s+\\w+\\s*\\(", NULL)))) {
    { StradaValue *__retval = strada_new_int(1);
        return __retval; }
}
{ StradaValue *__retval = strada_new_int(0);
    return __retval; }
}


StradaValue* is_package_decl(StradaValue* input) {
if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "^\\s*package\\s+\\w+", NULL)))) {
    { StradaValue *__retval = strada_new_int(1);
        return __retval; }
}
{ StradaValue *__retval = strada_new_int(0);
    return __retval; }
}


StradaValue* is_import(StradaValue* input) {
if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "^\\s*(use|import_lib|import_object)\\s+", NULL)))) {
    { StradaValue *__retval = strada_new_int(1);
        return __retval; }
}
{ StradaValue *__retval = strada_new_int(0);
    return __retval; }
}


StradaValue* get_var_decl_type(StradaValue* input, StradaValue* sigil) {
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("$"))) == 0))) {
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), strada_to_str(strada_new_str("my\\s+int\\s+\\")), NULL)))) {
        { StradaValue *__retval = strada_new_str("int");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), strada_to_str(strada_new_str("my\\s+num\\s+\\")), NULL)))) {
        { StradaValue *__retval = strada_new_str("num");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), strada_to_str(strada_new_str("my\\s+str\\s+\\")), NULL)))) {
        { StradaValue *__retval = strada_new_str("str");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), strada_to_str(strada_new_str("my\\s+scalar\\s+\\")), NULL)))) {
        { StradaValue *__retval = strada_new_str("scalar");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), strada_to_str(strada_new_str("my\\s+\\")), NULL)))) {
        { StradaValue *__retval = strada_new_str("scalar");
            return __retval; }
    }
} else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("@"))) == 0))) {
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "my\\s+array\\s+\\@", NULL)))) {
        { StradaValue *__retval = strada_new_str("array");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "my\\s+\\@", NULL)))) {
        { StradaValue *__retval = strada_new_str("array");
            return __retval; }
    }
} else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("%"))) == 0))) {
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "my\\s+hash\\s+\\%", NULL)))) {
        { StradaValue *__retval = strada_new_str("hash");
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(input), "my\\s+\\%", NULL)))) {
        { StradaValue *__retval = strada_new_str("hash");
            return __retval; }
    }
}
{ StradaValue *__retval = strada_new_str("");
    return __retval; }
}


StradaValue* generate_eval_source(StradaValue* input, StradaValue* state) {
StradaValue *src = strada_new_str("");
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("package REPL_Eval;\n\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
{
    StradaValue *__foreach_arr_0 = g_functions;
    StradaArray *__foreach_av_0 = strada_deref_array(__foreach_arr_0);
    int __foreach_len_0 = strada_array_length(__foreach_av_0);
    for (int __foreach_i_0 = 0; __foreach_i_0 < __foreach_len_0; __foreach_i_0++) {
        StradaValue *fn = strada_array_get(__foreach_av_0, __foreach_i_0);
        ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = strada_concat_sv(src, fn); StradaValue *__concat_r = strada_new_str("\n\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
    }
}
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("func repl_eval(scalar $__state) scalar {\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
{
    StradaValue *__foreach_arr_1 = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(g_var_types)));
    StradaArray *__foreach_av_1 = strada_deref_array(__foreach_arr_1);
    int __foreach_len_1 = strada_array_length(__foreach_av_1);
    for (int __foreach_i_1 = 0; __foreach_i_1 < __foreach_len_1; __foreach_i_1++) {
        StradaValue *name = strada_array_get(__foreach_av_1, __foreach_i_1);
        StradaValue *type = strada_hash_get(strada_deref_hash(g_var_types), strada_to_str(name)); strada_incref(type);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("array"))) == 0))) {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    my array @"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = ();\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    if (exists($__state, \""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\")) {\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("        @"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = @{$__state->{\""); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"}};\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("    }\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("hash"))) == 0))) {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    my hash %"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = ();\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    if (exists($__state, \""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\")) {\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("        %"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = %{$__state->{\""); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"}};\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("    }\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        } else {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    my "); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, type); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" $"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = undef;\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    if (exists($__state, \""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\")) {\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("        $"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = $__state->{\""); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"};\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("    }\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        }
        strada_decref(type);
    }
}
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("\n    # User code\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
StradaValue *trimmed = input; strada_incref(trimmed);
trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "\\s+$", "", NULL));
if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(trimmed), strada_to_str(strada_new_str(";")), NULL)))) {
    ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    "); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, input); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
    ({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("    my scalar $__result = undef;\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
} else {
    ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    my scalar $__result = "); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, input); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(";\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
}
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("\n    # Export variables back to state\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
{
    StradaValue *__foreach_arr_2 = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(g_var_types)));
    StradaArray *__foreach_av_2 = strada_deref_array(__foreach_arr_2);
    int __foreach_len_2 = strada_array_length(__foreach_av_2);
    for (int __foreach_i_2 = 0; __foreach_i_2 < __foreach_len_2; __foreach_i_2++) {
        StradaValue *name = strada_array_get(__foreach_av_2, __foreach_i_2);
        StradaValue *type = strada_hash_get(strada_deref_hash(g_var_types), strada_to_str(name)); strada_incref(type);
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("array"))) == 0))) {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    $__state->{\""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"} = \\@"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(";\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("hash"))) == 0))) {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    $__state->{\""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"} = \\%"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(";\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        } else {
            ({ StradaValue *__old = src; src = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("    $__state->{\""); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\"} = $"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(";\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
        }
        strada_decref(type);
    }
}
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("\n    return $__result;\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
({ StradaValue *__old = src; src = ({ StradaValue *__concat_r = strada_new_str("}\n"); StradaValue *__concat_res = strada_concat_sv(src, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); src; });
{ StradaValue *__retval = src;
    strada_incref(__retval);
    strada_decref(src);
    strada_decref(trimmed);
    return __retval; }
strada_decref(src);
strada_decref(trimmed);
}


void register_variables(StradaValue* input) {
StradaValue *pos = strada_new_int(0);
StradaValue *len = strada_new_int(strada_length_sv(input));
while ((strada_to_num(pos) < strada_to_num(len))) {
    StradaValue *my_pos = strada_new_int(strada_index_offset(strada_to_str(input), strada_to_str(strada_new_str("my ")), strada_to_int(pos)));
    if ((strada_to_num(my_pos) < 0.0)) {
        break;
    }
    ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(my_pos) + 3.0); strada_decref(__old); pos; });
    while (((strada_to_num(pos) < strada_to_num(len)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str(" "))) == 0)))) {
        ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
    }
    StradaValue *type = strada_new_str("scalar");
    StradaValue *next_word = strada_new_str("");
    StradaValue *word_start = pos; strada_incref(word_start);
    while ((strada_to_num(pos) < strada_to_num(len))) {
        StradaValue *c = strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)));
        if ((((strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str(" "))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("$"))) == 0))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("@"))) == 0))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("%"))) == 0)))) {
            break;
        }
        ({ StradaValue *__old = next_word; next_word = strada_concat_sv(next_word, c); strada_decref(__old); next_word; });
        ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
        strada_decref(c);
    }
    if ((((strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("int"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("num"))) == 0))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("str"))) == 0))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("scalar"))) == 0)))) {
        ({ StradaValue *__old = type; type = next_word; strada_incref(type); strada_decref(__old); type; });
        while (((strada_to_num(pos) < strada_to_num(len)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str(" "))) == 0)))) {
            ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
        }
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("array"))) == 0))) {
        ({ StradaValue *__old = type; type = strada_new_str("array"); strada_decref(__old); type; });
        while (((strada_to_num(pos) < strada_to_num(len)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str(" "))) == 0)))) {
            ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
        }
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(next_word), strada_to_str(strada_new_str("hash"))) == 0))) {
        ({ StradaValue *__old = type; type = strada_new_str("hash"); strada_decref(__old); type; });
        while (((strada_to_num(pos) < strada_to_num(len)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str(" "))) == 0)))) {
            ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
        }
    } else {
        ({ StradaValue *__old = pos; pos = word_start; strada_incref(pos); strada_decref(__old); pos; });
    }
    if ((strada_to_num(pos) >= strada_to_num(len))) {
        break;
    }
    StradaValue *sigil = strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("$"))) == 0))) {
        if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("array"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("hash"))) == 0)))) {
        }
        ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("@"))) == 0))) {
        ({ StradaValue *__old = type; type = strada_new_str("array"); strada_decref(__old); type; });
        ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
    } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(sigil), strada_to_str(strada_new_str("%"))) == 0))) {
        ({ StradaValue *__old = type; type = strada_new_str("hash"); strada_decref(__old); type; });
        ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
    } else {
        continue;
    }
    StradaValue *name = strada_new_str("");
    while ((strada_to_num(pos) < strada_to_num(len))) {
        StradaValue *c = strada_substr(input, strada_to_int(pos), strada_to_int(strada_new_int(1)));
        if (strada_to_bool(strada_new_int(strada_regex_match_with_capture(strada_to_str(c), "[a-zA-Z0-9_]", NULL)))) {
            ({ StradaValue *__old = name; name = strada_concat_sv(name, c); strada_decref(__old); name; });
            ({ StradaValue *__old = pos; pos = strada_new_num(strada_to_num(pos) + 1.0); strada_decref(__old); pos; });
        } else {
            break;
        }
        strada_decref(c);
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(name), strada_to_str(strada_new_str(""))) != 0))) {
        ({ StradaValue *__arg0 = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("Registering variable: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, type); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" "); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, sigil); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); repl_debug(__arg0); strada_decref(__arg0); });
        strada_hash_set(strada_deref_hash(g_var_types), strada_to_str(name), type);
    }
    strada_decref(my_pos);
    strada_decref(type);
    strada_decref(next_word);
    strada_decref(word_start);
    strada_decref(sigil);
    strada_decref(name);
}
strada_decref(pos);
strada_decref(len);
}


StradaValue* eval_input(StradaValue* input, StradaValue* state) {
({ StradaValue *__old = g_eval_count; g_eval_count = strada_new_num(strada_to_num(g_eval_count) + 1.0); strada_decref(__old); g_eval_count; });
StradaValue *base = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("/strada_repl_"); StradaValue *__concat_res = strada_concat_sv(g_tmpdir, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, g_eval_count); strada_decref(__concat_l); __concat_res; });
StradaValue *src_file = ({ StradaValue *__concat_r = strada_new_str(".strada"); StradaValue *__concat_res = strada_concat_sv(base, __concat_r); strada_decref(__concat_r); __concat_res; });
StradaValue *so_file = ({ StradaValue *__concat_r = strada_new_str(".so"); StradaValue *__concat_res = strada_concat_sv(base, __concat_r); strada_decref(__concat_r); __concat_res; });
register_variables(input);
StradaValue *src = generate_eval_source(input, state);
({ StradaValue *__arg0 = ({ StradaValue *__concat_l = strada_new_str("Generated source:\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, src); strada_decref(__concat_l); __concat_res; }); repl_debug(__arg0); strada_decref(__arg0); });
StradaValue *fd = strada_open(strada_to_str(src_file), strada_to_str(strada_new_str("w")));
if ((strada_to_num(fd) < 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("Error: Could not create temp file"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_undef();
        strada_incref(__retval);
        strada_decref(base);
        strada_decref(src_file);
        strada_decref(so_file);
        strada_decref(src);
        strada_decref(fd);
        return __retval; }
}
strada_write_fd(fd, src);
strada_close(fd);
StradaValue *compile_cmd = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("./strada --shared "); StradaValue *__concat_res = strada_concat_sv(__concat_l, src_file); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" 2>&1"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; });
StradaValue *compile_output = strada_popen(compile_cmd, strada_new_str("r"));
if ((strada_to_num(strada_is_file(so_file)) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("Compilation error:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_say(compile_output);
    strada_unlink(src_file);
    { StradaValue *__retval = strada_new_undef();
        strada_incref(__retval);
        strada_decref(base);
        strada_decref(src_file);
        strada_decref(so_file);
        strada_decref(src);
        strada_decref(fd);
        strada_decref(compile_cmd);
        strada_decref(compile_output);
        return __retval; }
}
StradaValue *lib = strada_dl_open(so_file);
if ((strada_to_num(lib) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("Error: Could not load compiled library"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_unlink(src_file);
    strada_unlink(so_file);
    { StradaValue *__retval = strada_new_undef();
        strada_incref(__retval);
        strada_decref(base);
        strada_decref(src_file);
        strada_decref(so_file);
        strada_decref(src);
        strada_decref(fd);
        strada_decref(compile_cmd);
        strada_decref(compile_output);
        strada_decref(lib);
        return __retval; }
}
StradaValue *fn = strada_dl_sym(lib, strada_new_str("REPL_Eval_repl_eval"));
if ((strada_to_num(fn) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("Error: Could not find eval function"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_dl_close(lib);
    strada_unlink(src_file);
    strada_unlink(so_file);
    { StradaValue *__retval = strada_new_undef();
        strada_incref(__retval);
        strada_decref(base);
        strada_decref(src_file);
        strada_decref(so_file);
        strada_decref(src);
        strada_decref(fd);
        strada_decref(compile_cmd);
        strada_decref(compile_output);
        strada_decref(lib);
        strada_decref(fn);
        return __retval; }
}
StradaValue *result = strada_new_undef();
if (setjmp(*STRADA_TRY_PUSH()) == 0) {
    ({ StradaValue *__old = result; result = strada_dl_call_sv(fn, state); strada_decref(__old); result; });
    STRADA_TRY_POP();
} else {
    STRADA_TRY_POP();
    StradaValue *__strada_exc = strada_get_exception();
    {
        StradaValue *e = __strada_exc;
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Runtime error: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, e); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        strada_decref(e);
    }
}
strada_dl_close(lib);
if ((strada_to_num(g_debug) == 0.0)) {
    strada_unlink(src_file);
    strada_unlink(so_file);
}
{ StradaValue *__retval = result;
    strada_incref(__retval);
    strada_decref(base);
    strada_decref(src_file);
    strada_decref(so_file);
    strada_decref(src);
    strada_decref(fd);
    strada_decref(compile_cmd);
    strada_decref(compile_output);
    strada_decref(lib);
    strada_decref(fn);
    strada_decref(result);
    return __retval; }
strada_decref(base);
strada_decref(src_file);
strada_decref(so_file);
strada_decref(src);
strada_decref(fd);
strada_decref(compile_cmd);
strada_decref(compile_output);
strada_decref(lib);
strada_decref(fn);
strada_decref(result);
}


StradaValue* format_value(StradaValue* val) {
if (!(strada_to_bool(strada_defined(val)))) {
    { StradaValue *__retval = strada_new_str("undef");
        return __retval; }
}
if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_typeof(val)), strada_to_str(strada_new_str("int"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_typeof(val)), strada_to_str(strada_new_str("num"))) == 0)))) {
    { StradaValue *__retval = ({ StradaValue *__concat_l = strada_new_str(""); StradaValue *__concat_res = strada_concat_sv(__concat_l, val); strada_decref(__concat_l); __concat_res; });
        return __retval; }
}
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_typeof(val)), strada_to_str(strada_new_str("str"))) == 0))) {
    { StradaValue *__retval = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("\""); StradaValue *__concat_res = strada_concat_sv(__concat_l, val); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str("\""); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; });
        return __retval; }
}
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_typeof(val)), strada_to_str(strada_new_str("array"))) == 0))) {
    StradaValue *s = strada_new_str("(");
    StradaValue *first = strada_new_int(1);
    StradaValue *i = strada_new_int(0);
    StradaValue *len = strada_new_int(strada_array_length(strada_deref_array(strada_deref_array_value(val))));
    while ((strada_to_num(i) < strada_to_num(len))) {
        if ((strada_to_num(first) == 0.0)) {
            ({ StradaValue *__old = s; s = ({ StradaValue *__concat_r = strada_new_str(", "); StradaValue *__concat_res = strada_concat_sv(s, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); s; });
        }
        ({ StradaValue *__old = s; s = strada_concat_sv(s, format_value(strada_array_get(strada_deref_array(val), strada_to_int(i)))); strada_decref(__old); s; });
        ({ StradaValue *__old = first; first = strada_new_int(0); strada_decref(__old); first; });
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    }
    ({ StradaValue *__old = s; s = ({ StradaValue *__concat_r = strada_new_str(")"); StradaValue *__concat_res = strada_concat_sv(s, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); s; });
    { StradaValue *__retval = s;
        strada_incref(__retval);
        strada_decref(s);
        strada_decref(first);
        strada_decref(i);
        strada_decref(len);
        return __retval; }
    strada_decref(s);
    strada_decref(first);
    strada_decref(i);
    strada_decref(len);
}
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_typeof(val)), strada_to_str(strada_new_str("hash"))) == 0))) {
    StradaValue *s = strada_new_str("{");
    StradaValue *first = strada_new_int(1);
    {
        StradaValue *__foreach_arr_3 = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(strada_deref_hash_value(val))));
        StradaArray *__foreach_av_3 = strada_deref_array(__foreach_arr_3);
        int __foreach_len_3 = strada_array_length(__foreach_av_3);
        for (int __foreach_i_3 = 0; __foreach_i_3 < __foreach_len_3; __foreach_i_3++) {
            StradaValue *k = strada_array_get(__foreach_av_3, __foreach_i_3);
            if ((strada_to_num(first) == 0.0)) {
                ({ StradaValue *__old = s; s = ({ StradaValue *__concat_r = strada_new_str(", "); StradaValue *__concat_res = strada_concat_sv(s, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); s; });
            }
            ({ StradaValue *__old = s; s = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_concat_sv(s, k); StradaValue *__concat_r = strada_new_str(" => "); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, format_value(strada_hash_get(strada_deref_hash(val), strada_to_str(k)))); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); s; });
            ({ StradaValue *__old = first; first = strada_new_int(0); strada_decref(__old); first; });
        }
    }
    ({ StradaValue *__old = s; s = ({ StradaValue *__concat_r = strada_new_str("}"); StradaValue *__concat_res = strada_concat_sv(s, __concat_r); strada_decref(__concat_r); __concat_res; }); strada_decref(__old); s; });
    { StradaValue *__retval = s;
        strada_incref(__retval);
        strada_decref(s);
        strada_decref(first);
        return __retval; }
    strada_decref(s);
    strada_decref(first);
}
StradaValue *class = strada_new_str(strada_reftype(val));
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(class), strada_to_str(strada_new_str(""))) != 0))) {
    { StradaValue *__retval = ({ StradaValue *__concat_r = strada_new_str("={...}"); StradaValue *__concat_res = strada_concat_sv(class, __concat_r); strada_decref(__concat_r); __concat_res; });
        strada_decref(class);
        return __retval; }
}
{ StradaValue *__retval = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("<"); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_typeof(val)); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(">"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; });
    strada_decref(class);
    return __retval; }
strada_decref(class);
}


StradaValue* is_balanced(StradaValue* input) {
StradaValue *braces = strada_new_int(0);
StradaValue *parens = strada_new_int(0);
StradaValue *brackets = strada_new_int(0);
StradaValue *in_string = strada_new_int(0);
StradaValue *len = strada_new_int(strada_length_sv(input));
StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < strada_to_num(len))) {
    StradaValue *c = strada_substr(input, strada_to_int(i), strada_to_int(strada_new_int(1)));
    if (((strada_to_num(i) > 0.0) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(input, strada_to_int(strada_new_num(strada_to_num(i) - 1.0)), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str("\\"))) == 0)))) {
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
        continue;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("\""))) == 0))) {
        ({ StradaValue *__old = in_string; in_string = strada_new_num(1.0 - strada_to_num(in_string)); strada_decref(__old); in_string; });
    }
    if ((strada_to_num(in_string) == 0.0)) {
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("{"))) == 0))) {
            ({ StradaValue *__old = braces; braces = strada_new_num(strada_to_num(braces) + 1.0); strada_decref(__old); braces; });
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("}"))) == 0))) {
            ({ StradaValue *__old = braces; braces = strada_new_num(strada_to_num(braces) - 1.0); strada_decref(__old); braces; });
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("("))) == 0))) {
            ({ StradaValue *__old = parens; parens = strada_new_num(strada_to_num(parens) + 1.0); strada_decref(__old); parens; });
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str(")"))) == 0))) {
            ({ StradaValue *__old = parens; parens = strada_new_num(strada_to_num(parens) - 1.0); strada_decref(__old); parens; });
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("["))) == 0))) {
            ({ StradaValue *__old = brackets; brackets = strada_new_num(strada_to_num(brackets) + 1.0); strada_decref(__old); brackets; });
        }
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(c), strada_to_str(strada_new_str("]"))) == 0))) {
            ({ StradaValue *__old = brackets; brackets = strada_new_num(strada_to_num(brackets) - 1.0); strada_decref(__old); brackets; });
        }
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(c);
}
if ((((strada_to_num(braces) == 0.0) && (strada_to_num(parens) == 0.0)) && (strada_to_num(brackets) == 0.0))) {
    { StradaValue *__retval = strada_new_int(1);
        strada_decref(braces);
        strada_decref(parens);
        strada_decref(brackets);
        strada_decref(in_string);
        strada_decref(len);
        strada_decref(i);
        return __retval; }
}
{ StradaValue *__retval = strada_new_int(0);
    strada_decref(braces);
    strada_decref(parens);
    strada_decref(brackets);
    strada_decref(in_string);
    strada_decref(len);
    strada_decref(i);
    return __retval; }
strada_decref(braces);
strada_decref(parens);
strada_decref(brackets);
strada_decref(in_string);
strada_decref(len);
strada_decref(i);
}


void print_help(void) {
({ StradaValue *__say_tmp = strada_new_str("Strada REPL - Interactive Strada Shell"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Commands:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .help     - Show this help"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .vars     - List declared variables"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .funcs    - List defined functions"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .clear    - Clear all state"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .debug    - Toggle debug mode"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  .quit     - Exit REPL"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Examples:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  my int $x = 42;"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  $x * 2"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  my array @nums = (1, 2, 3);"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  func double(int $n) int { return $n * 2; }"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
}


StradaValue* read_line(void) {
{ StradaValue *__retval = strada_readline();
    return __retval; }
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Initialize global variables */
    g_var_types = strada_new_hash();
    g_functions = strada_new_array();
    g_eval_count = strada_new_int(0);
    g_tmpdir = strada_new_str("/tmp");
    g_debug = strada_new_int(0);

({ StradaValue *__say_tmp = strada_new_str("Strada REPL v0.1"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Type .help for help, .quit to exit"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *state = strada_new_hash();
StradaValue *buffer = strada_new_str("");
StradaValue *continuation = strada_new_int(0);
while (1) {
    if ((strada_to_num(continuation) == 1.0)) {
        ({ StradaValue *__print_tmp = strada_new_str("...   "); strada_print(__print_tmp); strada_decref(__print_tmp); });
    } else {
        ({ StradaValue *__print_tmp = strada_new_str("strada> "); strada_print(__print_tmp); strada_decref(__print_tmp); });
    }
    StradaValue *line = read_line();
    if (!(strada_to_bool(strada_defined(line)))) {
        ({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
        break;
    }
    if ((strada_to_num(continuation) == 1.0)) {
        ({ StradaValue *__old = buffer; buffer = ({ StradaValue *__concat_l = ({ StradaValue *__concat_r = strada_new_str("\n"); StradaValue *__concat_res = strada_concat_sv(buffer, __concat_r); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, line); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); buffer; });
    } else {
        ({ StradaValue *__old = buffer; buffer = line; strada_incref(buffer); strada_decref(__old); buffer; });
    }
    if ((strada_to_num(is_balanced(buffer)) == 0.0)) {
        ({ StradaValue *__old = continuation; continuation = strada_new_int(1); strada_decref(__old); continuation; });
        continue;
    }
    ({ StradaValue *__old = continuation; continuation = strada_new_int(0); strada_decref(__old); continuation; });
    StradaValue *input = buffer; strada_incref(input);
    input = strada_new_str(strada_regex_replace(strada_to_str(input), "^\\s+", "", NULL));
    input = strada_new_str(strada_regex_replace(strada_to_str(input), "\\s+$", "", NULL));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(""))) == 0))) {
        continue;
    }
    if (((strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".quit"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".exit"))) == 0))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".q"))) == 0)))) {
        ({ StradaValue *__say_tmp = strada_new_str("Goodbye!"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        break;
    }
    if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".help"))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".h"))) == 0)))) {
        print_help();
        continue;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".vars"))) == 0))) {
        if ((({ StradaValue *__num_tmp = strada_new_int(strada_array_length(strada_deref_array(strada_new_array_from_av(strada_hash_keys(strada_deref_hash(g_var_types)))))); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0)) {
            ({ StradaValue *__say_tmp = strada_new_str("No variables declared"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        } else {
            ({ StradaValue *__say_tmp = strada_new_str("Variables:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
            {
                StradaValue *__foreach_arr_4 = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(g_var_types)));
                StradaArray *__foreach_av_4 = strada_deref_array(__foreach_arr_4);
                int __foreach_len_4 = strada_array_length(__foreach_av_4);
                for (int __foreach_i_4 = 0; __foreach_i_4 < __foreach_len_4; __foreach_i_4++) {
                    StradaValue *name = strada_array_get(__foreach_av_4, __foreach_i_4);
                    StradaValue *type = strada_hash_get(strada_deref_hash(g_var_types), strada_to_str(name)); strada_incref(type);
                    StradaValue *sigil = strada_new_str("$");
                    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("array"))) == 0))) {
                        ({ StradaValue *__old = sigil; sigil = strada_new_str("@"); strada_decref(__old); sigil; });
                    }
                    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(type), strada_to_str(strada_new_str("hash"))) == 0))) {
                        ({ StradaValue *__old = sigil; sigil = strada_new_str("%"); strada_decref(__old); sigil; });
                    }
                    StradaValue *val = strada_new_undef();
                    if (strada_to_bool(strada_new_int(strada_hash_exists(strada_deref_hash(state), strada_to_str(name))))) {
                        ({ StradaValue *__old = val; val = strada_hash_get(strada_deref_hash(state), strada_to_str(name)); strada_decref(__old); val; });
                    }
                    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("  "); StradaValue *__concat_res = strada_concat_sv(__concat_l, type); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" "); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, sigil); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, name); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, format_value(val)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
                    strada_decref(type);
                    strada_decref(sigil);
                    strada_decref(val);
                }
            }
        }
        continue;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".funcs"))) == 0))) {
        if ((({ StradaValue *__num_tmp = strada_new_int(strada_array_length(strada_deref_array(g_functions))); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0)) {
            ({ StradaValue *__say_tmp = strada_new_str("No functions defined"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        } else {
            ({ StradaValue *__say_tmp = strada_new_str("Functions:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
            {
                StradaValue *__foreach_arr_5 = g_functions;
                StradaArray *__foreach_av_5 = strada_deref_array(__foreach_arr_5);
                int __foreach_len_5 = strada_array_length(__foreach_av_5);
                for (int __foreach_i_5 = 0; __foreach_i_5 < __foreach_len_5; __foreach_i_5++) {
                    StradaValue *fn = strada_array_get(__foreach_av_5, __foreach_i_5);
                    StradaValue *brace = strada_new_int(strada_index(strada_to_str(fn), strada_to_str(strada_new_str("{"))));
                    StradaValue *sig = fn; strada_incref(sig);
                    if ((strada_to_num(brace) > 0.0)) {
                        ({ StradaValue *__old = sig; sig = strada_substr(fn, strada_to_int(strada_new_int(0)), strada_to_int(brace)); strada_decref(__old); sig; });
                    }
                    sig = strada_new_str(strada_regex_replace(strada_to_str(sig), "\\s+$", "", NULL));
                    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  "); StradaValue *__concat_res = strada_concat_sv(__concat_l, sig); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
                    strada_decref(brace);
                    strada_decref(sig);
                }
            }
        }
        continue;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".clear"))) == 0))) {
        ({ StradaValue *__old = g_var_types; g_var_types = strada_anon_hash(0); strada_decref(__old); g_var_types; });
        g_functions = strada_new_array();
        ({ StradaValue *__old = state; state = strada_anon_hash(0); strada_decref(__old); state; });
        ({ StradaValue *__say_tmp = strada_new_str("State cleared"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        continue;
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(input), strada_to_str(strada_new_str(".debug"))) == 0))) {
        ({ StradaValue *__old = g_debug; g_debug = strada_new_num(1.0 - strada_to_num(g_debug)); strada_decref(__old); g_debug; });
        if ((strada_to_num(g_debug) == 1.0)) {
            ({ StradaValue *__say_tmp = strada_new_str("Debug mode ON"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        } else {
            ({ StradaValue *__say_tmp = strada_new_str("Debug mode OFF"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        }
        continue;
    }
    if (strada_to_bool(is_function_def(input))) {
        (strada_array_push(strada_deref_array(g_functions), input), strada_new_undef());
        ({ StradaValue *__say_tmp = strada_new_str("Function defined"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        continue;
    }
    if (strada_to_bool(is_package_decl(input))) {
        ({ StradaValue *__say_tmp = strada_new_str("Package declarations are ignored in REPL"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        continue;
    }
    if (strada_to_bool(is_import(input))) {
        ({ StradaValue *__say_tmp = strada_new_str("Import statements are not yet supported in REPL"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        continue;
    }
    StradaValue *result = ({ StradaValue *__arg1 = strada_new_ref(state, '%'); StradaValue *__call_result = eval_input(input, __arg1); strada_decref(__arg1); __call_result; });
    if (strada_to_bool(strada_defined(result))) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("=> "); StradaValue *__concat_res = strada_concat_sv(__concat_l, format_value(result)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    }
    strada_decref(line);
    strada_decref(input);
    strada_decref(result);
}
strada_decref(state);
strada_decref(buffer);
strada_decref(continuation);
return 0;
strada_decref(state);
strada_decref(buffer);
strada_decref(continuation);
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:repl_debug:void:1:str:-1\nfunc:is_function_def:int:1:str:-1\nfunc:is_package_decl:int:1:str:-1\nfunc:is_import:int:1:str:-1\nfunc:get_var_decl_type:str:2:str,str:-1\nfunc:generate_eval_source:str:2:str,scalar:-1\nfunc:register_variables:void:1:str:-1\nfunc:eval_input:scalar:2:str,scalar:-1\nfunc:format_value:str:1:scalar:-1\nfunc:is_balanced:int:1:str:-1\nfunc:print_help:void:0::-1\nfunc:read_line:str:0::-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
