/*
 This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 Copyright (c) 2026 Michael J. Flickinger
 
 This program is free software: you can redistribute it and/or modify  
 it under the terms of the GNU General Public License as published by  
 the Free Software Foundation, version 2.

 This program is distributed in the hope that it will be useful, but 
 WITHOUT ANY WARRANTY; without even the implied warranty of 
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 General Public License for more details.

 You should have received a copy of the GNU General Public License 
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;

/* Global variables */
StradaValue *g_perl_bridge = NULL;
StradaValue *g_handler_sub = NULL;
StradaValue *g_cannoli_pm_path = NULL;
StradaValue *g_init_fn = NULL;
StradaValue *g_add_inc_fn = NULL;
StradaValue *g_use_fn = NULL;
StradaValue *g_do_fn = NULL;
StradaValue *g_load_cannoli_fn = NULL;
StradaValue *g_call_handler_fn = NULL;

StradaValue* config_get(StradaValue* config, StradaValue* key);
StradaValue* config_get_all(StradaValue* config, StradaValue* key);
StradaValue* find_bridge_path(void);
StradaValue* find_cannoli_pm_path(void);
StradaValue* cannoli_init(StradaValue* config);
StradaValue* strada_dispatch_impl(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* query_string, StradaValue* body, StradaValue* headers, StradaValue* remote_addr, StradaValue* content_type);

StradaValue* config_get(StradaValue* config, StradaValue* key) {
    StradaValue *key_len = strada_new_int(strada_length(strada_to_str(key)));
    StradaValue *config_len = strada_new_int(strada_length(strada_to_str(config)));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
            StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(" "))) != 0)))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) != 0))))) {
                break;
            }
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        if (strada_to_bool(strada_new_int(strada_to_num(i) >= strada_to_num(config_len)))) {
            break;
        }
        if (strada_to_bool(strada_new_int(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) < strada_to_num(config_len)))) {
            StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
            StradaValue *after_key = strada_substr(config, strada_to_int(strada_new_num(strada_to_num(i) + strada_to_num(key_len))), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(maybe_key), strada_to_str(key)) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(after_key), strada_to_str(strada_new_str("="))) == 0))))) {
                StradaValue *value_start = strada_new_num(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) + strada_to_num(strada_new_int(1)));
                StradaValue *value_end = value_start;
                while (strada_to_bool(strada_new_int(strada_to_num(value_end) < strada_to_num(config_len)))) {
                    StradaValue *ch = strada_substr(config, strada_to_int(value_end), strada_to_int(strada_new_int(1)));
                    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                        break;
                    }
                    value_end = strada_new_num(strada_to_num(value_end) + strada_to_num(strada_new_int(1)));
                }
                return strada_substr(config, strada_to_int(value_start), strada_to_int(strada_new_num(strada_to_num(value_end) - strada_to_num(value_start))));
            }
        }
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
            StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                break;
            }
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
    }
    return strada_new_str("");
}

StradaValue* config_get_all(StradaValue* config, StradaValue* key) {
    StradaValue *values = strada_new_array();
    StradaValue *key_len = strada_new_int(strada_length(strada_to_str(key)));
    StradaValue *config_len = strada_new_int(strada_length(strada_to_str(config)));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
            StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(" "))) != 0)))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) != 0))))) {
                break;
            }
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
        if (strada_to_bool(strada_new_int(strada_to_num(i) >= strada_to_num(config_len)))) {
            break;
        }
        if (strada_to_bool(strada_new_int(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) < strada_to_num(config_len)))) {
            StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
            StradaValue *after_key = strada_substr(config, strada_to_int(strada_new_num(strada_to_num(i) + strada_to_num(key_len))), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(maybe_key), strada_to_str(key)) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(after_key), strada_to_str(strada_new_str("="))) == 0))))) {
                StradaValue *value_start = strada_new_num(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) + strada_to_num(strada_new_int(1)));
                StradaValue *value_end = value_start;
                while (strada_to_bool(strada_new_int(strada_to_num(value_end) < strada_to_num(config_len)))) {
                    StradaValue *ch = strada_substr(config, strada_to_int(value_end), strada_to_int(strada_new_int(1)));
                    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                        break;
                    }
                    value_end = strada_new_num(strada_to_num(value_end) + strada_to_num(strada_new_int(1)));
                }
                StradaValue *value = strada_substr(config, strada_to_int(value_start), strada_to_int(strada_new_num(strada_to_num(value_end) - strada_to_num(value_start))));
                (strada_array_push(strada_deref_array(strada_new_ref(values, '@')), value), strada_new_undef());
            }
        }
        while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(config_len)))) {
            StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                break;
            }
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
        }
    }
    return values;
}

StradaValue* find_bridge_path(void) {
    if (strada_to_bool(strada_is_file(strada_new_str("./lib/perl/libperl_bridge.so")))) {
        return strada_new_str("./lib/perl/libperl_bridge.so");
    }
    if (strada_to_bool(strada_is_file(strada_new_str("./cannoli/lib/perl/libperl_bridge.so")))) {
        return strada_new_str("./cannoli/lib/perl/libperl_bridge.so");
    }
    if (strada_to_bool(strada_is_file(strada_new_str("/usr/local/lib/cannoli/libperl_bridge.so")))) {
        return strada_new_str("/usr/local/lib/cannoli/libperl_bridge.so");
    }
    return strada_new_str("libperl_bridge.so");
}

StradaValue* find_cannoli_pm_path(void) {
    if (strada_to_bool(strada_is_file(strada_new_str("./lib/perl/Cannoli.pm")))) {
        return strada_new_str("./lib/perl/Cannoli.pm");
    }
    if (strada_to_bool(strada_is_file(strada_new_str("./cannoli/lib/perl/Cannoli.pm")))) {
        return strada_new_str("./cannoli/lib/perl/Cannoli.pm");
    }
    if (strada_to_bool(strada_is_file(strada_new_str("/usr/local/lib/cannoli/Cannoli.pm")))) {
        return strada_new_str("/usr/local/lib/cannoli/Cannoli.pm");
    }
    return strada_new_str("");
}

StradaValue* cannoli_init(StradaValue* config) {
    g_handler_sub = config_get(config, strada_new_str("handler"));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(g_handler_sub)))) == strada_to_num(strada_new_int(0))))) {
        strada_say(strada_new_str("cannoli_perl: ERROR - Missing required 'handler' parameter"));
        strada_say(strada_new_str("Usage: --library ./cannoli_perl.so:handler=MyApp::handle"));
        return strada_new_int(0);
    }
    StradaValue *bridge_path = find_bridge_path();
    g_perl_bridge = strada_dl_open(bridge_path);
    if (strada_to_bool(strada_new_int(strada_to_num(g_perl_bridge) == strada_to_num(strada_new_int(0))))) {
        strada_say(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("cannoli_perl: ERROR - Could not load ")), strada_to_str(bridge_path))));
        strada_say(strada_new_str("  Make sure libperl_bridge.so is built and accessible"));
        return strada_new_int(0);
    }
    g_init_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_init"));
    g_add_inc_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_add_inc"));
    g_use_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_use"));
    g_do_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_do"));
    g_load_cannoli_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_load_cannoli"));
    g_call_handler_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_call_handler"));
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_num(g_init_fn) == strada_to_num(strada_new_int(0)))) || strada_to_bool(strada_new_int(strada_to_num(g_call_handler_fn) == strada_to_num(strada_new_int(0))))))) {
        strada_say(strada_new_str("cannoli_perl: ERROR - Bridge functions not found"));
        return strada_new_int(0);
    }
    StradaValue *init_result = strada_dl_call_int(g_init_fn, strada_new_str("init"));
    if (strada_to_bool(strada_new_int(strada_to_num(init_result) == strada_to_num(strada_new_int(0))))) {
        strada_say(strada_new_str("cannoli_perl: ERROR - Perl initialization failed"));
        return strada_new_int(0);
    }
    StradaValue *lib_paths = config_get_all(config, strada_new_str("lib"));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_new_int(strada_array_length(strada_deref_array(lib_paths))))))) {
        StradaValue *lib_path = strada_array_get(lib_paths->value.av, strada_to_int(i));
        strada_dl_call_int_sv(g_add_inc_fn, strada_anon_array(1, lib_path));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    g_cannoli_pm_path = find_cannoli_pm_path();
    if (strada_to_bool(strada_new_int(strada_to_num(g_load_cannoli_fn) != strada_to_num(strada_new_int(0))))) {
        StradaValue *load_result = strada_dl_call_int_sv(g_load_cannoli_fn, strada_anon_array(1, g_cannoli_pm_path));
        if (strada_to_bool(strada_new_int(strada_to_num(load_result) == strada_to_num(strada_new_int(0))))) {
            strada_say(strada_new_str("cannoli_perl: ERROR - Failed to load Cannoli.pm"));
            return strada_new_int(0);
        }
    }
    StradaValue *modules = config_get_all(config, strada_new_str("use"));
    i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_new_int(strada_array_length(strada_deref_array(modules))))))) {
        StradaValue *module = strada_array_get(modules->value.av, strada_to_int(i));
        StradaValue *use_result = strada_dl_call_int_sv(g_use_fn, strada_anon_array(1, module));
        if (strada_to_bool(strada_new_int(strada_to_num(use_result) == strada_to_num(strada_new_int(0))))) {
            strada_say(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("cannoli_perl: ERROR - Failed to use ")), strada_to_str(module))));
            return strada_new_int(0);
        }
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    StradaValue *script = config_get(config, strada_new_str("script"));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(script)))) > strada_to_num(strada_new_int(0))))) {
        StradaValue *do_result = strada_dl_call_int_sv(g_do_fn, strada_anon_array(1, script));
        if (strada_to_bool(strada_new_int(strada_to_num(do_result) == strada_to_num(strada_new_int(0))))) {
            strada_say(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("cannoli_perl: ERROR - Failed to load ")), strada_to_str(script))));
            return strada_new_int(0);
        }
    }
    return strada_new_int(1);
}

StradaValue* strada_dispatch_impl(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* query_string, StradaValue* body, StradaValue* headers, StradaValue* remote_addr, StradaValue* content_type) {
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_to_num(g_call_handler_fn) == strada_to_num(strada_new_int(0)))) || strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(g_handler_sub)))) == strada_to_num(strada_new_int(0))))))) {
        return strada_new_str("");
    }
    StradaValue *result = strada_dl_call_str_sv(g_call_handler_fn, strada_anon_array(9, g_handler_sub, method, path, path_info, query_string, body, headers, remote_addr, content_type));
    return result;
}

