/*
 * This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 * Copyright (c) 2026 Michael J. Flickinger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Generated by Strada Bootstrap Compiler */
/* Package: Math::Utils */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* @INC paths: */
/*   lib */

StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_subtract(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_square(StradaValue* n);
StradaValue* Math_Utils_factorial(StradaValue* n);

StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) + strada_to_num(b));
}

StradaValue* Math_Utils_subtract(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) - strada_to_num(b));
}

StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) * strada_to_num(b));
}

StradaValue* Math_Utils_square(StradaValue* n) {
    return strada_new_num(strada_to_num(n) * strada_to_num(n));
}

StradaValue* Math_Utils_factorial(StradaValue* n) {
    if (strada_to_bool(strada_new_int(strada_to_num(n) <= strada_to_num(strada_new_int(1))))) {
        return 1;
    }
    return strada_new_num(strada_to_num(n) * strada_to_num(Math_Utils_factorial(strada_new_num(strada_to_num(n) - strada_to_num(strada_new_int(1))))));
}

