/* Generated by Strada Self-Hosting Compiler */
/* Package: Nun */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;

void Nun_exec(StradaValue* t2);


/* OOP method registration forward declarations */
void __Nun_oop_init(void);
void Nun_exec(StradaValue* t2) {
StradaValue *moo = strada_new_undef();
({ StradaValue *__old = moo; moo = strada_new_str("undefd"); strada_decref(__old); moo; });
strada_dumper(strada_anon_hash(2, "string2", strada_new_ref(t2, '@'), "pope", moo));
strada_decref(moo);
}



/* OOP method dispatch helper */
static StradaValue* __strada_get_arg(StradaValue* args, int idx) {
    if (!args || args->type != STRADA_ARRAY) return NULL;
    if ((size_t)idx >= args->value.av->size) return NULL;
    return args->value.av->elements[idx];
}

/* OOP method wrappers for package Nun */
static StradaValue* __wrap_Nun_exec(StradaValue* self, StradaValue* args) {
    (void)args;
    Nun_exec(self);
    return strada_new_undef();
}

/* OOP method registration initializer */
static int __Nun_oop_initialized = 0;
void __Nun_oop_init(void) {
    if (__Nun_oop_initialized) return;
    __Nun_oop_initialized = 1;

    strada_method_register("Nun", "exec", __wrap_Nun_exec);
}

/* Qualified name aliases for package Nun */
void Nun__Nun_exec(StradaValue* t2) { return Nun_exec(t2); }


/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "func:Nun_exec:void:1:str:0\n";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}
