/*
 * This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 * Copyright (c) 2026 Michael J. Flickinger
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;

StradaValue* add(StradaValue* a, StradaValue* b);
StradaValue* greet(StradaValue* name);
StradaValue* factorial(StradaValue* n);
StradaValue* sum_array(StradaValue* arr);
StradaValue* fibonacci(StradaValue* n);

StradaValue* add(StradaValue* a, StradaValue* b) {
    return strada_new_num(strada_to_num(a) + strada_to_num(b));
}

StradaValue* greet(StradaValue* name) {
    return strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("Hello, ")), strada_to_str(name)))), strada_to_str(strada_new_str("!"))));
}

StradaValue* factorial(StradaValue* n) {
    if (strada_to_bool(strada_new_int(strada_to_num(n) <= strada_to_num(strada_new_int(1))))) {
        return strada_new_int(1);
    }
    return strada_new_num(strada_to_num(n) * strada_to_num(factorial(strada_new_num(strada_to_num(n) - strada_to_num(strada_new_int(1))))));
}

StradaValue* sum_array(StradaValue* arr) {
    StradaValue *total = strada_new_int(0);
    StradaValue *len = strada_new_int(strada_array_length(strada_deref_array(arr)));
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(len)))) {
        total = strada_new_num(strada_to_num(total) + strada_to_num(strada_array_get(strada_deref_array(arr), strada_to_int(i))));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    return total;
}

StradaValue* fibonacci(StradaValue* n) {
    if (strada_to_bool(strada_new_int(strada_to_num(n) <= strada_to_num(strada_new_int(1))))) {
        return n;
    }
    return strada_new_num(strada_to_num(fibonacci(strada_new_num(strada_to_num(n) - strada_to_num(strada_new_int(1))))) + strada_to_num(fibonacci(strada_new_num(strada_to_num(n) - strada_to_num(strada_new_int(2))))));
}

