/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

StradaValue* process_array(StradaValue* arr);
StradaValue* process_hash(StradaValue* h);
int main(int _argc, char **_argv);

StradaValue* process_array(StradaValue* arr) {
strada_incref(arr);
{ StradaValue *__retval = strada_new_int(strada_array_length(strada_deref_array(arr)));
    strada_decref(arr);
    return __retval; }
}


StradaValue* process_hash(StradaValue* h) {
strada_incref(h);
StradaValue *keys = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(h)));
{ StradaValue *__retval = strada_new_int(strada_array_length(strada_deref_array(keys)));
    strada_decref(keys);
    strada_decref(h);
    return __retval; }
strada_decref(keys);
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < 1000.0)) {
    if (({ StradaValue *__def_tmp = strada_safe_div(10.0, 3.0); int __def_res = strada_defined_bool(__def_tmp); strada_decref(__def_tmp); __def_res; })) {
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    if (({ StradaValue *__def_tmp = strada_safe_div(10.0, 0.0); int __def_res = strada_defined_bool(__def_tmp); strada_decref(__def_tmp); __def_res; })) {
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *len = ({ StradaValue *__len_tmp = ({ StradaValue *__concat_l = strada_new_str("hello"); StradaValue *__concat_r = strada_new_str("world"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); char *__len_str = strada_to_str(__len_tmp); int64_t __len_res = strada_length(__len_str); free(__len_str); strada_decref(__len_tmp); strada_new_int(__len_res); });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(len);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *len = ({ StradaValue *__sc_tmp = ({ StradaValue *__aa_el0 = strada_new_int(1); StradaValue *__aa_el1 = strada_new_int(2); StradaValue *__aa_el2 = strada_new_int(3); StradaValue *__aa_arr = strada_anon_array(3, __aa_el0, __aa_el1, __aa_el2); strada_decref(__aa_el0); strada_decref(__aa_el1); strada_decref(__aa_el2); __aa_arr; }); int64_t __sc_res = strada_array_length(strada_deref_array(__sc_tmp)); strada_decref(__sc_tmp); strada_new_int(__sc_res); });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(len);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *type = ({ StradaValue *__ref_tmp = ({ StradaValue *__aa_el0 = strada_new_int(1); StradaValue *__aa_el1 = strada_new_int(2); StradaValue *__aa_el2 = strada_new_int(3); StradaValue *__aa_arr = strada_anon_array(3, __aa_el0, __aa_el1, __aa_el2); strada_decref(__aa_el0); strada_decref(__aa_el1); strada_decref(__aa_el2); __aa_arr; }); StradaValue *__ref_res = strada_new_str(strada_reftype(__ref_tmp)); strada_decref(__ref_tmp); __ref_res; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(type);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *len = ({ StradaValue *__arg0 = ({ StradaValue *__aa_el0 = strada_new_int(1); StradaValue *__aa_el1 = strada_new_int(2); StradaValue *__aa_el2 = strada_new_int(3); StradaValue *__aa_el3 = strada_new_int(4); StradaValue *__aa_el4 = strada_new_int(5); StradaValue *__aa_arr = strada_anon_array(5, __aa_el0, __aa_el1, __aa_el2, __aa_el3, __aa_el4); strada_decref(__aa_el0); strada_decref(__aa_el1); strada_decref(__aa_el2); strada_decref(__aa_el3); strada_decref(__aa_el4); __aa_arr; }); StradaValue *__call_result = process_array(__arg0); strada_decref(__arg0); __call_result; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(len);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *count = ({ StradaValue *__arg0 = ({ StradaValue *__ah_val0 = strada_new_int(1); StradaValue *__ah_val1 = strada_new_int(2); StradaValue *__ah_val2 = strada_new_int(3); StradaValue *__ah_hash = strada_anon_hash(3, "a", __ah_val0, "b", __ah_val1, "c", __ah_val2); strada_decref(__ah_val0); strada_decref(__ah_val1); strada_decref(__ah_val2); __ah_hash; }); StradaValue *__call_result = process_hash(__arg0); strada_decref(__arg0); __call_result; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(count);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *arr = ({ StradaValue *__aa_el0 = strada_new_int(10); StradaValue *__aa_el1 = strada_new_int(20); StradaValue *__aa_el2 = strada_new_int(30); StradaValue *__aa_arr = strada_anon_array(3, __aa_el0, __aa_el1, __aa_el2); strada_decref(__aa_el0); strada_decref(__aa_el1); strada_decref(__aa_el2); __aa_arr; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(arr);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *h = ({ StradaValue *__ah_val0 = strada_new_int(1); StradaValue *__ah_val1 = strada_new_int(2); StradaValue *__ah_hash = strada_anon_hash(2, "x", __ah_val0, "y", __ah_val1); strada_decref(__ah_val0); strada_decref(__ah_val1); __ah_hash; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(h);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *nested = ({ StradaValue *__aa_el0 = ({ StradaValue *__aa_el0 = strada_new_int(1); StradaValue *__aa_el1 = strada_new_int(2); StradaValue *__aa_arr = strada_anon_array(2, __aa_el0, __aa_el1); strada_decref(__aa_el0); strada_decref(__aa_el1); __aa_arr; }); StradaValue *__aa_el1 = ({ StradaValue *__aa_el0 = strada_new_int(3); StradaValue *__aa_el1 = strada_new_int(4); StradaValue *__aa_arr = strada_anon_array(2, __aa_el0, __aa_el1); strada_decref(__aa_el0); strada_decref(__aa_el1); __aa_arr; }); StradaValue *__aa_arr = strada_anon_array(2, __aa_el0, __aa_el1); strada_decref(__aa_el0); strada_decref(__aa_el1); __aa_arr; });
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(nested);
}
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < 1000.0)) {
    StradaValue *result = strada_safe_mod((int64_t)10, (int64_t)0);
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(result);
}
({ StradaValue *__say_tmp = strada_new_str("PASS: Temporary cleanup test completed"); strada_say(__say_tmp); strada_decref(__say_tmp); });
strada_decref(i);
return 0;
strada_decref(i);
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:process_array:int:1:scalar:-1\nfunc:process_hash:int:1:scalar:-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
