/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

/* Global variables and constants */
static StradaValue *MAX_SIZE = NULL;
static StradaValue *VERSION = NULL;
static StradaValue *PI = NULL;
static StradaValue *LIMIT = NULL;

void test_global_consts(void);
void test_local_consts(void);
void test_const_in_expressions(void);
void test_const_in_conditionals(void);
int main(int _argc, char **_argv);

void test_global_consts(void) {
strada_stack_push("test_global_consts", "test_const.strada");
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("MAX_SIZE: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, MAX_SIZE); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("VERSION: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, VERSION); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("PI: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, PI); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("LIMIT: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, LIMIT); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
if ((strada_to_num(MAX_SIZE) != 100.0)) {
    strada_die("%s", strada_to_str(strada_new_str("MAX_SIZE should be 100")));
}
if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(VERSION, "1.0.0")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    strada_die("%s", strada_to_str(strada_new_str("VERSION should be 1.0.0")));
}
if ((strada_to_num(LIMIT) != 50.0)) {
    strada_die("%s", strada_to_str(strada_new_str("LIMIT should be 50")));
}
strada_stack_pop();
}


void test_local_consts(void) {
strada_stack_push("test_local_consts", "test_const.strada");
StradaValue *LOCAL_MAX = strada_new_int(25);
StradaValue *LOCAL_NAME = strada_new_str("test");
StradaValue *LOCAL_PI = PI;
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("LOCAL_MAX: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, LOCAL_MAX); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("LOCAL_NAME: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, LOCAL_NAME); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("LOCAL_PI: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, LOCAL_PI); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
if ((strada_to_num(LOCAL_MAX) != 25.0)) {
    strada_die("%s", strada_to_str(strada_new_str("LOCAL_MAX should be 25")));
}
if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(LOCAL_NAME, "test")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    strada_die("%s", strada_to_str(strada_new_str("LOCAL_NAME should be test")));
}
strada_decref(LOCAL_MAX);
strada_decref(LOCAL_NAME);
strada_decref(LOCAL_PI);
strada_stack_pop();
}


void test_const_in_expressions(void) {
strada_stack_push("test_const_in_expressions", "test_const.strada");
StradaValue *doubled = strada_new_num(strada_to_num(MAX_SIZE) * 2.0);
StradaValue *half = strada_safe_div(strada_to_num(LIMIT), 2.0);
StradaValue *msg = ({ StradaValue *__concat_l = strada_new_str("Version is "); StradaValue *__concat_res = strada_concat_sv(__concat_l, VERSION); strada_decref(__concat_l); __concat_res; });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("doubled: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, doubled); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("half: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, half); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("msg: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, msg); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
if ((strada_to_num(doubled) != 200.0)) {
    strada_die("%s", strada_to_str(strada_new_str("doubled should be 200")));
}
if ((strada_to_num(half) != 25.0)) {
    strada_die("%s", strada_to_str(strada_new_str("half should be 25")));
}
strada_decref(doubled);
strada_decref(half);
strada_decref(msg);
strada_stack_pop();
}


void test_const_in_conditionals(void) {
strada_stack_push("test_const_in_conditionals", "test_const.strada");
if ((strada_to_num(MAX_SIZE) > 50.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("MAX_SIZE is greater than 50"); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else {
    strada_die("%s", strada_to_str(strada_new_str("Conditional with const failed")));
}
StradaValue *x = strada_new_int(75);
if ((strada_to_num(x) < strada_to_num(MAX_SIZE))) {
    ({ StradaValue *__say_tmp = strada_new_str("x is less than MAX_SIZE"); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else {
    strada_die("%s", strada_to_str(strada_new_str("Comparison with const failed")));
}
strada_decref(x);
strada_stack_pop();
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    strada_stack_push("main", "test_const.strada");

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Initialize global variables */
    MAX_SIZE = strada_new_int(100);
    VERSION = strada_new_str("1.0.0");
    PI = strada_new_num(3.14159);
    LIMIT = strada_new_int(50);

({ StradaValue *__say_tmp = strada_new_str("Testing const declarations..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
test_global_consts();
test_local_consts();
test_const_in_expressions();
test_const_in_conditionals();
({ StradaValue *__say_tmp = strada_new_str("All const tests passed!"); strada_say(__say_tmp); strada_decref(__say_tmp); });
strada_stack_pop();
return 0;
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:test_global_consts:void:0::-1\nfunc:test_local_consts:void:0::-1\nfunc:test_const_in_expressions:void:0::-1\nfunc:test_const_in_conditionals:void:0::-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
