/* Generated by Strada Self-Hosting Compiler */
/* Package: MyLib::Utils */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

extern int compute(int a, int b);
StradaValue* MyLib_Utils_helper(StradaValue* x);
StradaValue* MyLib_Utils_process(StradaValue* val);
StradaValue* MyLib_Utils_strada_compute(StradaValue* a, StradaValue* b);
int main(int _argc, char **_argv);


/* OOP method registration forward declarations */
void __MyLib_Utils_oop_init(void);
int compute(int a, int b) {
    return (a + b);
}

StradaValue* MyLib_Utils_helper(StradaValue* x) {
strada_incref(x);
{ StradaValue *__retval = strada_new_num(strada_to_num(x) * 2.0);
    strada_decref(x);
    return __retval; }
}


StradaValue* MyLib_Utils_process(StradaValue* val) {
strada_incref(val);
{ StradaValue *__retval = strada_new_num(strada_to_num(MyLib_Utils_helper(val)) + 10.0);
    strada_decref(val);
    return __retval; }
}


StradaValue* MyLib_Utils_strada_compute(StradaValue* a, StradaValue* b) {
strada_incref(a);
strada_incref(b);
{ StradaValue *__retval = strada_new_num(strada_to_num(a) + strada_to_num(b));
    strada_decref(a);
    strada_decref(b);
    return __retval; }
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Set package from file-level declaration */
    strada_set_package("MyLib::Utils");

    /* Initialize OOP method registration */
    __MyLib_Utils_oop_init();

({ StradaValue *__say_tmp = strada_new_str("Testing extern package functions:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  strada_compute(5, 3) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, ({ StradaValue *__arg0 = strada_new_int(5); StradaValue *__arg1 = strada_new_int(3); StradaValue *__call_result = strada_compute(__arg0, __arg1); strada_decref(__arg0); strada_decref(__arg1); __call_result; })); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  helper(7) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, ({ StradaValue *__arg0 = strada_new_int(7); StradaValue *__call_result = helper(__arg0); strada_decref(__arg0); __call_result; })); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  process(4) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, ({ StradaValue *__arg0 = strada_new_int(4); StradaValue *__call_result = process(__arg0); strada_decref(__arg0); __call_result; })); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Note: extern func 'compute' is for C interop, not Strada calls."); strada_say(__say_tmp); strada_decref(__say_tmp); });
return 0;
}


/* OOP method dispatch helper */
static StradaValue* __strada_get_arg(StradaValue* args, int idx) {
    if (!args || args->type != STRADA_ARRAY) return NULL;
    if ((size_t)idx >= args->value.av->size) return NULL;
    return args->value.av->elements[idx];
}

/* OOP method wrappers for package MyLib::Utils */
static StradaValue* __wrap_MyLib_Utils_helper(StradaValue* self, StradaValue* args) {
    (void)args;
    return MyLib_Utils_helper(self);
}

static StradaValue* __wrap_MyLib_Utils_process(StradaValue* self, StradaValue* args) {
    (void)args;
    return MyLib_Utils_process(self);
}

static StradaValue* __wrap_MyLib_Utils_strada_compute(StradaValue* self, StradaValue* args) {
    return MyLib_Utils_strada_compute(self, __strada_get_arg(args, 0));
}

/* OOP method registration initializer */
static int __MyLib_Utils_oop_initialized = 0;
void __MyLib_Utils_oop_init(void) {
    if (__MyLib_Utils_oop_initialized) return;
    __MyLib_Utils_oop_initialized = 1;

    strada_method_register("MyLib::Utils", "helper", __wrap_MyLib_Utils_helper);
    strada_method_register("MyLib::Utils", "process", __wrap_MyLib_Utils_process);
    strada_method_register("MyLib::Utils", "strada_compute", __wrap_MyLib_Utils_strada_compute);
}

/* Qualified name aliases for package MyLib::Utils */
StradaValue* MyLib__Utils__MyLib_Utils_helper(StradaValue* x) { return MyLib_Utils_helper(x); }
StradaValue* MyLib__Utils__MyLib_Utils_process(StradaValue* val) { return MyLib_Utils_process(val); }
StradaValue* MyLib__Utils__MyLib_Utils_strada_compute(StradaValue* a, StradaValue* b) { return MyLib_Utils_strada_compute(a, b); }


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:MyLib_Utils_helper:int:1:int:-1\nfunc:MyLib_Utils_process:int:1:int:-1\nfunc:MyLib_Utils_strada_compute:int:2:int,int:-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
