/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

int main(int _argc, char **_argv);

int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

({ StradaValue *__say_tmp = strada_new_str("Testing math operations for memory leaks..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *iterations = strada_new_int(100);
({ StradaValue *__say_tmp = strada_new_str("  Basic arithmetic..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *a = strada_new_int(10);
    StradaValue *b = strada_new_int(3);
    StradaValue *add = strada_new_num(strada_to_num(a) + strada_to_num(b));
    StradaValue *sub = strada_new_num(strada_to_num(a) - strada_to_num(b));
    StradaValue *mul = strada_new_num(strada_to_num(a) * strada_to_num(b));
    StradaValue *div = strada_safe_div(strada_to_num(a), strada_to_num(b));
    StradaValue *mod = strada_safe_mod((int64_t)strada_to_int(a), (int64_t)strada_to_int(b));
    if ((((((strada_to_num(add) != 13.0) || (strada_to_num(sub) != 7.0)) || (strada_to_num(mul) != 30.0)) || (strada_to_num(div) != 3.0)) || (strada_to_num(mod) != 1.0))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: basic arithmetic"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(add);
        strada_decref(sub);
        strada_decref(mul);
        strada_decref(div);
        strada_decref(mod);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(a);
    strada_decref(b);
    strada_decref(add);
    strada_decref(sub);
    strada_decref(mul);
    strada_decref(div);
    strada_decref(mod);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  Floating point..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *x = strada_new_num(3.14159);
    StradaValue *y = strada_new_num(2.71828);
    StradaValue *sum = strada_new_num(strada_to_num(x) + strada_to_num(y));
    StradaValue *prod = strada_new_num(strada_to_num(x) * strada_to_num(y));
    if (((strada_to_num(sum) < 5.8) || (strada_to_num(sum) > 5.9))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: float sum"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(x);
        strada_decref(y);
        strada_decref(sum);
        strada_decref(prod);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(x);
    strada_decref(y);
    strada_decref(sum);
    strada_decref(prod);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::sin/cos/tan..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *angle = strada_new_num(0.5);
    StradaValue *s = strada_sin(angle);
    StradaValue *c = strada_cos(angle);
    StradaValue *t = strada_tan(angle);
    if (((strada_to_num(s) < 0.47) || (strada_to_num(s) > 0.49))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: sin"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(angle);
        strada_decref(s);
        strada_decref(c);
        strada_decref(t);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (((strada_to_num(c) < 0.87) || (strada_to_num(c) > 0.89))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: cos"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(angle);
        strada_decref(s);
        strada_decref(c);
        strada_decref(t);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(angle);
    strada_decref(s);
    strada_decref(c);
    strada_decref(t);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::sqrt..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *sq = strada_sqrt(strada_new_num(16.0));
    if (((strada_to_num(sq) < 3.99) || (strada_to_num(sq) > 4.01))) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("    FAIL: sqrt(16) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, sq); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(sq);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    StradaValue *sq2 = strada_sqrt(strada_new_num(2.0));
    if (((strada_to_num(sq2) < 1.41) || (strada_to_num(sq2) > 1.42))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: sqrt(2)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(sq);
        strada_decref(sq2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(sq);
    strada_decref(sq2);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::pow..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *p1 = strada_pow(strada_new_num(2.0), strada_new_num(10.0));
    StradaValue *p2 = strada_pow(strada_new_num(3.0), strada_new_num(3.0));
    if (((strada_to_num(p1) < 1023.9) || (strada_to_num(p1) > 1024.1))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: pow(2,10)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(p1);
        strada_decref(p2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (((strada_to_num(p2) < 26.9) || (strada_to_num(p2) > 27.1))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: pow(3,3)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(p1);
        strada_decref(p2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(p1);
    strada_decref(p2);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::log/exp..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *lg = strada_log(strada_new_num(2.71828));
    StradaValue *ex = strada_exp(strada_new_num(1.0));
    if (((strada_to_num(lg) < 0.99) || (strada_to_num(lg) > 1.01))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: log(e)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(lg);
        strada_decref(ex);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (((strada_to_num(ex) < 2.71) || (strada_to_num(ex) > 2.72))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: exp(1)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(lg);
        strada_decref(ex);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(lg);
    strada_decref(ex);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::floor/ceil..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *f1 = strada_floor(strada_new_num(3.7));
    StradaValue *f2 = strada_floor(({ StradaValue *__unary_tmp = strada_new_num(3.7); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }));
    StradaValue *c1 = strada_ceil(strada_new_num(3.2));
    StradaValue *c2 = strada_ceil(({ StradaValue *__unary_tmp = strada_new_num(3.2); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }));
    if ((strada_to_num(f1) != 3.0)) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: floor(3.7)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(f1);
        strada_decref(f2);
        strada_decref(c1);
        strada_decref(c2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if ((strada_to_num(f2) != ({ StradaValue *__num_tmp = ({ StradaValue *__unary_tmp = strada_new_num(4.0); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: floor(-3.7)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(f1);
        strada_decref(f2);
        strada_decref(c1);
        strada_decref(c2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if ((strada_to_num(c1) != 4.0)) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: ceil(3.2)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(f1);
        strada_decref(f2);
        strada_decref(c1);
        strada_decref(c2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if ((strada_to_num(c2) != ({ StradaValue *__num_tmp = ({ StradaValue *__unary_tmp = strada_new_num(3.0); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: ceil(-3.2)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(f1);
        strada_decref(f2);
        strada_decref(c1);
        strada_decref(c2);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(f1);
    strada_decref(f2);
    strada_decref(c1);
    strada_decref(c2);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::abs..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *a1 = strada_abs(({ StradaValue *__unary_tmp = strada_new_num(5.5); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }));
    StradaValue *a2 = strada_abs(strada_new_num(5.5));
    StradaValue *a3 = strada_abs(({ StradaValue *__unary_tmp = strada_new_num(42.0); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }));
    if ((((strada_to_num(a1) != 5.5) || (strada_to_num(a2) != 5.5)) || (strada_to_num(a3) != 42.0))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: abs"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a1);
        strada_decref(a2);
        strada_decref(a3);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(a1);
    strada_decref(a2);
    strada_decref(a3);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  math::round..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *r1 = strada_round(strada_new_num(3.4));
    StradaValue *r2 = strada_round(strada_new_num(3.5));
    StradaValue *r3 = strada_round(({ StradaValue *__unary_tmp = strada_new_num(3.5); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }));
    if ((strada_to_num(r1) != 3.0)) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: round(3.4)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(r1);
        strada_decref(r2);
        strada_decref(r3);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if ((strada_to_num(r2) != 4.0)) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: round(3.5)"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(r1);
        strada_decref(r2);
        strada_decref(r3);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(r1);
    strada_decref(r2);
    strada_decref(r3);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  rand()..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *r = strada_rand();
    if ((strada_to_num(r) < 0.0)) {
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(r);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  Comparison operators..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *a = strada_new_int(5);
    StradaValue *b = strada_new_int(10);
    StradaValue *c = strada_new_int(5);
    if (!((strada_to_num(a) < strada_to_num(b)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: <"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (!((strada_to_num(b) > strada_to_num(a)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: >"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (!((strada_to_num(a) <= strada_to_num(c)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: <="); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (!((strada_to_num(a) >= strada_to_num(c)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: >="); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (!((strada_to_num(a) == strada_to_num(c)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: =="); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    if (!((strada_to_num(a) != strada_to_num(b)))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: !="); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(a);
        strada_decref(b);
        strada_decref(c);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(a);
    strada_decref(b);
    strada_decref(c);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("  Spaceship operator (<=>)..."); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(iterations))) {
    StradaValue *r1 = ({ StradaValue *__sp_lv = strada_new_int(5); StradaValue *__sp_rv = strada_new_int(10); double __l = strada_to_num(__sp_lv); double __r = strada_to_num(__sp_rv); strada_decref(__sp_lv); strada_decref(__sp_rv); strada_new_int((__l < __r) ? -1 : ((__l > __r) ? 1 : 0)); });
    StradaValue *r2 = ({ StradaValue *__sp_lv = strada_new_int(10); StradaValue *__sp_rv = strada_new_int(5); double __l = strada_to_num(__sp_lv); double __r = strada_to_num(__sp_rv); strada_decref(__sp_lv); strada_decref(__sp_rv); strada_new_int((__l < __r) ? -1 : ((__l > __r) ? 1 : 0)); });
    StradaValue *r3 = ({ StradaValue *__sp_lv = strada_new_int(5); StradaValue *__sp_rv = strada_new_int(5); double __l = strada_to_num(__sp_lv); double __r = strada_to_num(__sp_rv); strada_decref(__sp_lv); strada_decref(__sp_rv); strada_new_int((__l < __r) ? -1 : ((__l > __r) ? 1 : 0)); });
    if ((((strada_to_num(r1) != ({ StradaValue *__num_tmp = ({ StradaValue *__unary_tmp = strada_new_int(1); StradaValue *__unary_res = strada_new_num(-strada_to_num(__unary_tmp)); strada_decref(__unary_tmp); __unary_res; }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; })) || (strada_to_num(r2) != 1.0)) || (strada_to_num(r3) != 0.0))) {
        ({ StradaValue *__say_tmp = strada_new_str("    FAIL: <=>"); strada_say(__say_tmp); strada_decref(__say_tmp); });
                strada_decref(r1);
        strada_decref(r2);
        strada_decref(r3);
        strada_decref(iterations);
        strada_decref(i);
        return 1;
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(r1);
    strada_decref(r2);
    strada_decref(r3);
}
({ StradaValue *__say_tmp = strada_new_str("    PASS"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("All math tests passed!"); strada_say(__say_tmp); strada_decref(__say_tmp); });
strada_decref(iterations);
strada_decref(i);
return 0;
strada_decref(iterations);
strada_decref(i);
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
