/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

int main(int _argc, char **_argv);

int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

({ StradaValue *__say_tmp = strada_new_str("=== Arrays in boolean context ===\n"); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *queue = ({ StradaValue *__aa_el0 = strada_new_str("task1"); StradaValue *__aa_el1 = strada_new_str("task2"); StradaValue *__aa_el2 = strada_new_str("task3"); StradaValue *__aa_arr = strada_anon_array(3, __aa_el0, __aa_el1, __aa_el2); strada_decref(__aa_el0); strada_decref(__aa_el1); strada_decref(__aa_el2); __aa_arr; });
({ StradaValue *__say_tmp = strada_new_str("Processing queue:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
while (strada_to_bool(queue)) {
    StradaValue *task = strada_array_shift(strada_deref_array(queue));
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  Processing: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, task); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_decref(task);
}
({ StradaValue *__say_tmp = strada_new_str("Queue empty!\n"); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *results = strada_new_array();
if (strada_to_bool(results)) {
    ({ StradaValue *__say_tmp = strada_new_str("Has results"); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else {
    ({ StradaValue *__say_tmp = strada_new_str("No results yet"); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
({ StradaValue *__expr_tmp = ({ StradaValue *__push_v = strada_new_str("found something"); strada_array_push(strada_deref_array(results), __push_v); strada_decref(__push_v); strada_undef_static(); }); strada_decref(__expr_tmp); });
if (strada_to_bool(results)) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("Now has results: "); StradaValue *__concat_r = strada_new_int(strada_size(results)); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_r = strada_new_str(" item(s)\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
({ StradaValue *__say_tmp = strada_new_str("=== Hashes in boolean context ===\n"); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *todo = strada_new_hash();
({ StradaValue *__hset_v = strada_new_str("kitchen"); strada_hash_set(strada_deref_hash(todo), "dishes", __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_new_str("bedroom"); strada_hash_set(strada_deref_hash(todo), "laundry", __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_new_str("living room"); strada_hash_set(strada_deref_hash(todo), "vacuum", __hset_v); strada_decref(__hset_v); });
({ StradaValue *__say_tmp = strada_new_str("Completing chores:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
while (strada_to_bool(todo)) {
    StradaValue *tasks = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(todo)));
    StradaValue *task = strada_array_get(strada_deref_array(tasks), 0); strada_incref(task);
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("  Done: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, task); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_r = strada_new_str(" in "); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, ({ StradaValue *__hget_k = task; char *__hget_ks = strada_to_str(__hget_k); StradaValue *__hget_r = strada_hash_get(strada_deref_hash(todo), __hget_ks); free(__hget_ks); __hget_r; })); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__del_key = task; char *__del_key_str = strada_to_str(__del_key); strada_hash_delete(strada_deref_hash(todo), __del_key_str); free(__del_key_str); strada_undef_static(); });
    strada_decref(tasks);
    strada_decref(task);
}
({ StradaValue *__say_tmp = strada_new_str("All chores done!\n"); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *config = strada_new_hash();
if (strada_to_bool(config)) {
    ({ StradaValue *__say_tmp = strada_new_str("Config loaded"); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else {
    ({ StradaValue *__say_tmp = strada_new_str("No config - using defaults"); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
({ StradaValue *__hset_v = strada_new_str("true"); strada_hash_set(strada_deref_hash(config), "debug", __hset_v); strada_decref(__hset_v); });
if (strada_to_bool(config)) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_new_str("Config now has "); StradaValue *__concat_r = strada_new_int(strada_size(config)); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); StradaValue *__concat_r = strada_new_str(" setting(s)\n"); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
({ StradaValue *__say_tmp = strada_new_str("=== Combined conditions ===\n"); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *errors = strada_new_array();
StradaValue *warnings = strada_new_array(); { StradaValue *__arr_init_tmp = strada_new_str("minor issue"); strada_array_push(warnings->value.av, __arr_init_tmp); strada_decref(__arr_init_tmp); };
if ((strada_to_bool(errors) || strada_to_bool(warnings))) {
    ({ StradaValue *__say_tmp = strada_new_str("Issues found:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    if (strada_to_bool(errors)) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  Errors: "); StradaValue *__concat_r = strada_new_int(strada_size(errors)); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    }
    if (strada_to_bool(warnings)) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  Warnings: "); StradaValue *__concat_r = strada_new_int(strada_size(warnings)); StradaValue *__concat_res = strada_concat_sv(__concat_l, __concat_r); strada_decref(__concat_l); strada_decref(__concat_r); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    }
}
if ((!(strada_to_bool(errors)) && !(strada_to_bool(warnings)))) {
    ({ StradaValue *__say_tmp = strada_new_str("All clear!"); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else if (!(strada_to_bool(errors))) {
    ({ StradaValue *__say_tmp = strada_new_str("No errors, but has warnings"); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
({ StradaValue *__say_tmp = strada_new_str("\n=== All tests passed! ==="); strada_say(__say_tmp); strada_decref(__say_tmp); });
strada_decref(queue);
strada_decref(results);
strada_decref(todo);
strada_decref(config);
strada_decref(errors);
strada_decref(warnings);
return 0;
strada_decref(queue);
strada_decref(results);
strada_decref(todo);
strada_decref(config);
strada_decref(errors);
strada_decref(warnings);
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
