/* Generated by Strada Self-Hosting Compiler */
/* Package: Math::Utils */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b);
StradaValue* Math_Utils_square(StradaValue* x);
int main(int _argc, char **_argv);


/* OOP method registration forward declarations */
void __Math_Utils_oop_init(void);
StradaValue* Math_Utils_add(StradaValue* a, StradaValue* b) {
strada_incref(a);
strada_incref(b);
{ StradaValue *__retval = strada_new_num(strada_to_num(a) + strada_to_num(b));
    strada_decref(a);
    strada_decref(b);
    return __retval; }
}


StradaValue* Math_Utils_multiply(StradaValue* a, StradaValue* b) {
strada_incref(a);
strada_incref(b);
{ StradaValue *__retval = strada_new_num(strada_to_num(a) * strada_to_num(b));
    strada_decref(a);
    strada_decref(b);
    return __retval; }
}


StradaValue* Math_Utils_square(StradaValue* x) {
strada_incref(x);
{ StradaValue *__retval = strada_new_num(strada_to_num(x) * strada_to_num(x));
    strada_decref(x);
    return __retval; }
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Set package from file-level declaration */
    strada_set_package("Math::Utils");

    /* Initialize OOP method registration */
    __Math_Utils_oop_init();

({ StradaValue *__say_tmp = strada_new_str("Cross-Module Function Calls Test"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("================================="); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *x = strada_new_int(5);
StradaValue *y = strada_new_int(3);
({ StradaValue *__say_tmp = strada_new_str("Variables:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  x = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, x); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  y = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, y); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Function calls:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  add(x, y) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, add(x, y)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  multiply(x, y) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, multiply(x, y)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  square(x) = "); StradaValue *__concat_res = strada_concat_sv(__concat_l, square(x)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str(""); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = strada_new_str("Module test complete!"); strada_say(__say_tmp); strada_decref(__say_tmp); });
strada_decref(x);
strada_decref(y);
return 0;
strada_decref(x);
strada_decref(y);
}


/* OOP method dispatch helper */
static StradaValue* __strada_get_arg(StradaValue* args, int idx) {
    if (!args || args->type != STRADA_ARRAY) return NULL;
    if ((size_t)idx >= args->value.av->size) return NULL;
    return args->value.av->elements[idx];
}

/* OOP method wrappers for package Math::Utils */
static StradaValue* __wrap_Math_Utils_add(StradaValue* self, StradaValue* args) {
    return Math_Utils_add(self, __strada_get_arg(args, 0));
}

static StradaValue* __wrap_Math_Utils_multiply(StradaValue* self, StradaValue* args) {
    return Math_Utils_multiply(self, __strada_get_arg(args, 0));
}

static StradaValue* __wrap_Math_Utils_square(StradaValue* self, StradaValue* args) {
    (void)args;
    return Math_Utils_square(self);
}

/* OOP method registration initializer */
static int __Math_Utils_oop_initialized = 0;
void __Math_Utils_oop_init(void) {
    if (__Math_Utils_oop_initialized) return;
    __Math_Utils_oop_initialized = 1;

    strada_method_register("Math::Utils", "add", __wrap_Math_Utils_add);
    strada_method_register("Math::Utils", "multiply", __wrap_Math_Utils_multiply);
    strada_method_register("Math::Utils", "square", __wrap_Math_Utils_square);
}

/* Qualified name aliases for package Math::Utils */
StradaValue* Math__Utils__Math_Utils_add(StradaValue* a, StradaValue* b) { return Math_Utils_add(a, b); }
StradaValue* Math__Utils__Math_Utils_multiply(StradaValue* a, StradaValue* b) { return Math_Utils_multiply(a, b); }
StradaValue* Math__Utils__Math_Utils_square(StradaValue* x) { return Math_Utils_square(x); }


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:Math_Utils_add:int:2:int,int:-1\nfunc:Math_Utils_multiply:int:2:int,int:-1\nfunc:Math_Utils_square:int:1:int:-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
