/* Generated by Strada Self-Hosting Compiler */
/* Package: main */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

extern int bingo(char* moo);
int main(int _argc, char **_argv);

int bingo(char* moo) {
    ({ StradaValue *__say_tmp = strada_cstr_concat(strada_cstr_concat("so, cows go ", moo), ""); strada_say(__say_tmp); strada_decref(__say_tmp); });
    return 33;
}

int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Set package from file-level declaration */
    strada_set_package("main");

({ StradaValue *__print_tmp = strada_new_str("hello world\n"); strada_print(__print_tmp); strada_decref(__print_tmp); });
({ StradaValue *__sv_arg0 = strada_new_str("hello"); int __ext_ret = bingo(strada_to_str(__sv_arg0)); strada_decref(__sv_arg0); strada_new_int(__ext_ret); });
return 0;
}

/* Qualified name aliases for package main */


/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}
