/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

/* Qualified imports from Text::CSV */

StradaValue* Text_CSV__opt_str(StradaValue* opts, StradaValue* key, StradaValue* fallback);
StradaValue* Text_CSV__opt_int(StradaValue* opts, StradaValue* key, StradaValue* fallback);
StradaValue* Text_CSV_new(StradaValue* opts);
StradaValue* Text_CSV_error_diag(StradaValue* self);
StradaValue* Text_CSV_fields(StradaValue* self);
StradaValue* Text_CSV_string(StradaValue* self);
StradaValue* Text_CSV__strip_eol(StradaValue* line);
void Text_CSV__set_error(StradaValue* self, StradaValue* msg);
void Text_CSV__clear_buffer(StradaValue* self);
StradaValue* Text_CSV_parse(StradaValue* self, StradaValue* line);
StradaValue* Text_CSV_getline(StradaValue* self, StradaValue* fh);
StradaValue* Text_CSV__escape_field(StradaValue* field, StradaValue* quote, StradaValue* escape);
StradaValue* Text_CSV_combine(StradaValue* self, StradaValue* fields);
int main(int _argc, char **_argv);

StradaValue* Text_CSV__opt_str(StradaValue* opts, StradaValue* key, StradaValue* fallback) {
if ((strada_to_bool(strada_defined(opts)) && strada_to_bool(strada_defined(strada_hash_get(strada_deref_hash(opts), strada_to_str(key)))))) {
    { StradaValue *__retval = ({ StradaValue *__concat_l = strada_new_str(""); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_hash_get(strada_deref_hash(opts), strada_to_str(key))); strada_decref(__concat_l); __concat_res; });
        return __retval; }
}
{ StradaValue *__retval = fallback;
    strada_incref(__retval);
    return __retval; }
}


StradaValue* Text_CSV__opt_int(StradaValue* opts, StradaValue* key, StradaValue* fallback) {
if ((strada_to_bool(strada_defined(opts)) && strada_to_bool(strada_defined(strada_hash_get(strada_deref_hash(opts), strada_to_str(key)))))) {
    { StradaValue *__retval = strada_hash_get(strada_deref_hash(opts), strada_to_str(key));
        strada_incref(__retval);
        return __retval; }
}
{ StradaValue *__retval = fallback;
    strada_incref(__retval);
    return __retval; }
}


StradaValue* Text_CSV_new(StradaValue* opts) {
StradaValue *self = strada_new_hash();
({ StradaValue *__hset_v = ({ StradaValue *__arg1 = strada_new_str("sep_char"); StradaValue *__arg2 = strada_new_str(","); StradaValue *__call_result = Text_CSV__opt_str(opts, __arg1, __arg2); strada_decref(__arg1); strada_decref(__arg2); __call_result; }); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("sep_char")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = ({ StradaValue *__arg1 = strada_new_str("quote_char"); StradaValue *__arg2 = strada_new_str("\""); StradaValue *__call_result = Text_CSV__opt_str(opts, __arg1, __arg2); strada_decref(__arg1); strada_decref(__arg2); __call_result; }); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("quote_char")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = ({ StradaValue *__arg1 = strada_new_str("escape_char"); StradaValue *__arg2 = strada_new_str("\""); StradaValue *__call_result = Text_CSV__opt_str(opts, __arg1, __arg2); strada_decref(__arg1); strada_decref(__arg2); __call_result; }); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("escape_char")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = ({ StradaValue *__arg1 = strada_new_str("always_quote"); StradaValue *__arg2 = strada_new_int(0); StradaValue *__call_result = Text_CSV__opt_int(opts, __arg1, __arg2); strada_decref(__arg1); strada_decref(__arg2); __call_result; }); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("always_quote")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = ({ StradaValue *__arg1 = strada_new_str("binary"); StradaValue *__arg2 = strada_new_int(0); StradaValue *__call_result = Text_CSV__opt_int(opts, __arg1, __arg2); strada_decref(__arg1); strada_decref(__arg2); __call_result; }); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("binary")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_new_str(""); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("error")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_anon_array(0); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("fields")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_new_str(""); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("string")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_new_str(""); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("buffer")), __hset_v); strada_decref(__hset_v); });
{ StradaValue *__retval = strada_bless(strada_new_ref(self, '%'), strada_to_str(strada_new_str("Text::CSV")));
    strada_decref(self);
    return __retval; }
strada_decref(self);
}


StradaValue* Text_CSV_error_diag(StradaValue* self) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_new_str("No CSV object");
        return __retval; }
}
{ StradaValue *__retval = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("error")));
    strada_incref(__retval);
    return __retval; }
}


StradaValue* Text_CSV_fields(StradaValue* self) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_anon_array(0);
        return __retval; }
}
{ StradaValue *__retval = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("fields")));
    strada_incref(__retval);
    return __retval; }
}


StradaValue* Text_CSV_string(StradaValue* self) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_new_str("");
        return __retval; }
}
{ StradaValue *__retval = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("string")));
    strada_incref(__retval);
    return __retval; }
}


StradaValue* Text_CSV__strip_eol(StradaValue* line) {
StradaValue *len = strada_new_int(strada_length_sv(line));
if ((strada_to_num(len) == 0.0)) {
    { StradaValue *__retval = line;
        strada_incref(__retval);
        strada_decref(len);
        return __retval; }
}
if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(line, strada_to_int(strada_new_num(strada_to_num(len) - 1.0)), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str("\n"))) == 0))) {
    ({ StradaValue *__old = line; line = strada_substr(line, strada_to_int(strada_new_int(0)), strada_to_int(strada_new_num(strada_to_num(len) - 1.0))); strada_decref(__old); line; });
    ({ StradaValue *__old = len; len = strada_new_num(strada_to_num(len) - 1.0); strada_decref(__old); len; });
}
if (((strada_to_num(len) > 0.0) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(line, strada_to_int(strada_new_num(strada_to_num(len) - 1.0)), strada_to_int(strada_new_int(1)))), strada_to_str(strada_new_str("\r"))) == 0)))) {
    ({ StradaValue *__old = line; line = strada_substr(line, strada_to_int(strada_new_int(0)), strada_to_int(strada_new_num(strada_to_num(len) - 1.0))); strada_decref(__old); line; });
}
{ StradaValue *__retval = line;
    strada_incref(__retval);
    strada_decref(len);
    return __retval; }
strada_decref(len);
}


void Text_CSV__set_error(StradaValue* self, StradaValue* msg) {
if (strada_to_bool(strada_defined(self))) {
    strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("error")), msg);
    ({ StradaValue *__hset_v = strada_anon_array(0); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("fields")), __hset_v); strada_decref(__hset_v); });
}
}


void Text_CSV__clear_buffer(StradaValue* self) {
if (strada_to_bool(strada_defined(self))) {
    ({ StradaValue *__hset_v = strada_new_str(""); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("buffer")), __hset_v); strada_decref(__hset_v); });
}
}


StradaValue* Text_CSV_parse(StradaValue* self, StradaValue* line) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_new_int(0);
        return __retval; }
}
({ StradaValue *__hset_v = strada_new_str(""); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("error")), __hset_v); strada_decref(__hset_v); });
({ StradaValue *__hset_v = strada_anon_array(0); strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("fields")), __hset_v); strada_decref(__hset_v); });
StradaValue *sep = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("sep_char"))); strada_incref(sep);
StradaValue *quote = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("quote_char"))); strada_incref(quote);
StradaValue *escape = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("escape_char"))); strada_incref(escape);
({ StradaValue *__old = line; line = Text_CSV__strip_eol(line); strada_decref(__old); line; });
StradaValue *fields = strada_anon_array(0);
StradaValue *current = strada_new_str("");
StradaValue *in_quotes = strada_new_int(0);
StradaValue *i = strada_new_int(0);
StradaValue *len = strada_new_int(strada_length_sv(line));
while ((strada_to_num(i) < strada_to_num(len))) {
    StradaValue *ch = strada_substr(line, strada_to_int(i), strada_to_int(strada_new_int(1)));
    if (strada_to_bool(in_quotes)) {
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(quote)) == 0))) {
            if ((((strada_to_num(strada_new_num(strada_to_num(i) + 1.0)) < strada_to_num(len)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_substr(line, strada_to_int(strada_new_num(strada_to_num(i) + 1.0)), strada_to_int(strada_new_int(1)))), strada_to_str(quote)) == 0))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(quote)) == 0)))) {
                ({ StradaValue *__old = current; current = strada_concat_sv(current, quote); strada_decref(__old); current; });
                ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
            } else {
                ({ StradaValue *__old = in_quotes; in_quotes = strada_new_int(0); strada_decref(__old); in_quotes; });
            }
        } else if (((strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(strada_new_str(""))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(quote)) != 0))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(escape)) == 0)))) {
            if ((strada_to_num(strada_new_num(strada_to_num(i) + 1.0)) < strada_to_num(len))) {
                ({ StradaValue *__old = current; current = strada_concat_sv(current, strada_substr(line, strada_to_int(strada_new_num(strada_to_num(i) + 1.0)), strada_to_int(strada_new_int(1)))); strada_decref(__old); current; });
                ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
            } else {
                ({ StradaValue *__old = current; current = strada_concat_sv(current, ch); strada_decref(__old); current; });
            }
        } else {
            ({ StradaValue *__old = current; current = strada_concat_sv(current, ch); strada_decref(__old); current; });
        }
    } else {
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(sep)) == 0))) {
            (strada_array_push(strada_deref_array(fields), current), strada_new_undef());
            ({ StradaValue *__old = current; current = strada_new_str(""); strada_decref(__old); current; });
        } else if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(quote)) == 0))) {
            if (strada_to_bool(strada_new_int(strcmp(strada_to_str(current), strada_to_str(strada_new_str(""))) != 0))) {
                ({ StradaValue *__arg1 = strada_new_str("Unexpected quote in field"); StradaValue *__call_result = Text_CSV__set_error(self, __arg1); strada_decref(__arg1); __call_result; });
                { StradaValue *__retval = strada_new_int(0);
                    strada_decref(ch);
                    strada_decref(sep);
                    strada_decref(quote);
                    strada_decref(escape);
                    strada_decref(fields);
                    strada_decref(current);
                    strada_decref(in_quotes);
                    strada_decref(i);
                    strada_decref(len);
                    return __retval; }
            }
            ({ StradaValue *__old = in_quotes; in_quotes = strada_new_int(1); strada_decref(__old); in_quotes; });
        } else {
            ({ StradaValue *__old = current; current = strada_concat_sv(current, ch); strada_decref(__old); current; });
        }
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(ch);
}
if (strada_to_bool(in_quotes)) {
    ({ StradaValue *__arg1 = strada_new_str("Unmatched quote"); StradaValue *__call_result = Text_CSV__set_error(self, __arg1); strada_decref(__arg1); __call_result; });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(sep);
        strada_decref(quote);
        strada_decref(escape);
        strada_decref(fields);
        strada_decref(current);
        strada_decref(in_quotes);
        strada_decref(i);
        strada_decref(len);
        return __retval; }
}
(strada_array_push(strada_deref_array(fields), current), strada_new_undef());
strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("fields")), fields);
{ StradaValue *__retval = strada_new_int(1);
    strada_decref(sep);
    strada_decref(quote);
    strada_decref(escape);
    strada_decref(fields);
    strada_decref(current);
    strada_decref(in_quotes);
    strada_decref(i);
    strada_decref(len);
    return __retval; }
strada_decref(sep);
strada_decref(quote);
strada_decref(escape);
strada_decref(fields);
strada_decref(current);
strada_decref(in_quotes);
strada_decref(i);
strada_decref(len);
}


StradaValue* Text_CSV_getline(StradaValue* self, StradaValue* fh) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_new_undef();
        strada_incref(__retval);
        return __retval; }
}
StradaValue *buf = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("buffer"))); strada_incref(buf);
StradaValue *appended = strada_new_int(0);
while (1) {
    StradaValue *line = strada_read_line(fh);
    if ((!(strada_to_bool(strada_defined(line))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(line), strada_to_str(strada_new_str(""))) == 0)))) {
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(buf), strada_to_str(strada_new_str(""))) != 0))) {
            ({ StradaValue *__arg1 = strada_new_str("Unmatched quote"); StradaValue *__call_result = Text_CSV__set_error(self, __arg1); strada_decref(__arg1); __call_result; });
        }
        Text_CSV__clear_buffer(self);
        { StradaValue *__retval = strada_new_undef();
            strada_incref(__retval);
            strada_decref(line);
            strada_decref(buf);
            strada_decref(appended);
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(buf), strada_to_str(strada_new_str(""))) == 0))) {
        ({ StradaValue *__old = buf; buf = line; strada_incref(buf); strada_decref(__old); buf; });
    } else {
        ({ StradaValue *__old = buf; buf = strada_concat_sv(buf, line); strada_decref(__old); buf; });
    }
    ({ StradaValue *__old = appended; appended = strada_new_int(1); strada_decref(__old); appended; });
    if (strada_to_bool(Text_CSV_parse(self, buf))) {
        Text_CSV__clear_buffer(self);
        { StradaValue *__retval = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("fields")));
            strada_incref(__retval);
            strada_decref(line);
            strada_decref(buf);
            strada_decref(appended);
            return __retval; }
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("error")))), strada_to_str(strada_new_str("Unmatched quote"))) != 0))) {
        Text_CSV__clear_buffer(self);
        { StradaValue *__retval = strada_new_undef();
            strada_incref(__retval);
            strada_decref(line);
            strada_decref(buf);
            strada_decref(appended);
            return __retval; }
    }
    strada_decref(line);
}
strada_decref(buf);
strada_decref(appended);
}


StradaValue* Text_CSV__escape_field(StradaValue* field, StradaValue* quote, StradaValue* escape) {
StradaValue *out = strada_new_str("");
StradaValue *i = strada_new_int(0);
StradaValue *len = strada_new_int(strada_length_sv(field));
while ((strada_to_num(i) < strada_to_num(len))) {
    StradaValue *ch = strada_substr(field, strada_to_int(i), strada_to_int(strada_new_int(1)));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(quote)) == 0))) {
        if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(strada_new_str(""))) == 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(quote)) == 0)))) {
            ({ StradaValue *__old = out; out = ({ StradaValue *__concat_l = strada_concat_sv(out, quote); StradaValue *__concat_res = strada_concat_sv(__concat_l, quote); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); out; });
        } else {
            ({ StradaValue *__old = out; out = ({ StradaValue *__concat_l = strada_concat_sv(out, escape); StradaValue *__concat_res = strada_concat_sv(__concat_l, quote); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); out; });
        }
    } else if (((strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(strada_new_str(""))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(escape), strada_to_str(quote)) != 0))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(escape)) == 0)))) {
        ({ StradaValue *__old = out; out = ({ StradaValue *__concat_l = strada_concat_sv(out, escape); StradaValue *__concat_res = strada_concat_sv(__concat_l, escape); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); out; });
    } else {
        ({ StradaValue *__old = out; out = strada_concat_sv(out, ch); strada_decref(__old); out; });
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(ch);
}
{ StradaValue *__retval = out;
    strada_incref(__retval);
    strada_decref(out);
    strada_decref(i);
    strada_decref(len);
    return __retval; }
strada_decref(out);
strada_decref(i);
strada_decref(len);
}


StradaValue* Text_CSV_combine(StradaValue* self, StradaValue* fields) {
if (!(strada_to_bool(strada_defined(self)))) {
    { StradaValue *__retval = strada_new_int(0);
        return __retval; }
}
if ((!(strada_to_bool(strada_defined(fields))) || strada_to_bool(strada_new_int(strcmp(strada_to_str(strada_new_str(strada_reftype(fields))), strada_to_str(strada_new_str("array"))) != 0)))) {
    ({ StradaValue *__arg1 = strada_new_str("combine expects array reference"); StradaValue *__call_result = Text_CSV__set_error(self, __arg1); strada_decref(__arg1); __call_result; });
    { StradaValue *__retval = strada_new_int(0);
        return __retval; }
}
StradaValue *sep = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("sep_char"))); strada_incref(sep);
StradaValue *quote = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("quote_char"))); strada_incref(quote);
StradaValue *escape = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("escape_char"))); strada_incref(escape);
StradaValue *always_quote = strada_hash_get(strada_deref_hash(self), strada_to_str(strada_new_str("always_quote"))); strada_incref(always_quote);
StradaValue *out = strada_new_str("");
StradaValue *i = strada_new_int(0);
StradaValue *count = strada_new_int(strada_size(fields));
while ((strada_to_num(i) < strada_to_num(count))) {
    if ((strada_to_num(i) > 0.0)) {
        ({ StradaValue *__old = out; out = strada_concat_sv(out, sep); strada_decref(__old); out; });
    }
    StradaValue *field = ({ StradaValue *__concat_l = strada_new_str(""); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(fields), strada_to_int(i))); strada_decref(__concat_l); __concat_res; });
    StradaValue *need_quote = always_quote; strada_incref(need_quote);
    if ((strada_to_num(strada_new_int(strada_index(strada_to_str(field), strada_to_str(sep)))) >= 0.0)) {
        ({ StradaValue *__old = need_quote; need_quote = strada_new_int(1); strada_decref(__old); need_quote; });
    }
    if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(quote), strada_to_str(strada_new_str(""))) != 0)) && (strada_to_num(strada_new_int(strada_index(strada_to_str(field), strada_to_str(quote)))) >= 0.0))) {
        ({ StradaValue *__old = need_quote; need_quote = strada_new_int(1); strada_decref(__old); need_quote; });
    }
    if (((strada_to_num(strada_new_int(strada_index(strada_to_str(field), strada_to_str(strada_new_str("\n"))))) >= 0.0) || (strada_to_num(strada_new_int(strada_index(strada_to_str(field), strada_to_str(strada_new_str("\r"))))) >= 0.0))) {
        ({ StradaValue *__old = need_quote; need_quote = strada_new_int(1); strada_decref(__old); need_quote; });
    }
    StradaValue *escaped = Text_CSV__escape_field(field, quote, escape);
    if (strada_to_bool(need_quote)) {
        ({ StradaValue *__old = out; out = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_concat_sv(out, quote); StradaValue *__concat_res = strada_concat_sv(__concat_l, escaped); strada_decref(__concat_l); __concat_res; }); StradaValue *__concat_res = strada_concat_sv(__concat_l, quote); strada_decref(__concat_l); __concat_res; }); strada_decref(__old); out; });
    } else {
        ({ StradaValue *__old = out; out = strada_concat_sv(out, escaped); strada_decref(__old); out; });
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(field);
    strada_decref(need_quote);
    strada_decref(escaped);
}
strada_hash_set(strada_deref_hash(self), strada_to_str(strada_new_str("string")), out);
{ StradaValue *__retval = strada_new_int(1);
    strada_decref(sep);
    strada_decref(quote);
    strada_decref(escape);
    strada_decref(always_quote);
    strada_decref(out);
    strada_decref(i);
    strada_decref(count);
    return __retval; }
strada_decref(sep);
strada_decref(quote);
strada_decref(escape);
strada_decref(always_quote);
strada_decref(out);
strada_decref(i);
strada_decref(count);
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

StradaValue *csv = ({ StradaValue *__arg0 = strada_anon_hash(0); StradaValue *__call_result = Text_CSV_new(__arg0); strada_decref(__arg0); __call_result; });
StradaValue *line = strada_new_str("a,\"b\",c");
if (!(strada_to_bool(Text_CSV_parse(csv, line)))) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("parse error: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, Text_CSV_error_diag(csv)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_decref(csv);
    strada_decref(line);
    return 1;
}
StradaValue *fields = Text_CSV_fields(csv);
({ StradaValue *__say_tmp = strada_new_str("Parsed fields:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  0: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(fields), strada_to_int(strada_new_int(0)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  1: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(fields), strada_to_int(strada_new_int(1)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  2: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(fields), strada_to_int(strada_new_int(2)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *out_fields = strada_anon_array(3, strada_new_str("x"), strada_new_str("y,z"), strada_new_str("q\"u"));
if (!(strada_to_bool(Text_CSV_combine(csv, out_fields)))) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("combine error: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, Text_CSV_error_diag(csv)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    strada_decref(csv);
    strada_decref(line);
    strada_decref(fields);
    strada_decref(out_fields);
    return 1;
}
({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Combined: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, Text_CSV_string(csv)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
StradaValue *fh = strada_open(strada_to_str(strada_new_str("/tmp/text_csv_demo.csv")), strada_to_str(strada_new_str("w")));
strada_write_file(fh, strada_to_str(strada_new_str("a,\"multi\nline\",c\n")));
strada_close(fh);
({ StradaValue *__old = fh; fh = strada_open(strada_to_str(strada_new_str("/tmp/text_csv_demo.csv")), strada_to_str(strada_new_str("r"))); strada_decref(__old); fh; });
StradaValue *row = Text_CSV_getline(csv, fh);
strada_close(fh);
if (strada_to_bool(strada_defined(row))) {
    ({ StradaValue *__say_tmp = strada_new_str("Multiline row:"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  0: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(row), strada_to_int(strada_new_int(0)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  1: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(row), strada_to_int(strada_new_int(1)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("  2: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_array_get(strada_deref_array(row), strada_to_int(strada_new_int(2)))); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
} else {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("getline error: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, Text_CSV_error_diag(csv)); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
}
strada_decref(csv);
strada_decref(line);
strada_decref(fields);
strada_decref(out_fields);
strada_decref(fh);
strada_decref(row);
return 0;
strada_decref(csv);
strada_decref(line);
strada_decref(fields);
strada_decref(out_fields);
strada_decref(fh);
strada_decref(row);
}


/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "func:Text_CSV__opt_str:str:3:scalar,str,str\nfunc:Text_CSV__opt_int:int:3:scalar,str,int\nfunc:Text_CSV_new:scalar:1:scalar\nfunc:Text_CSV_error_diag:str:1:scalar\nfunc:Text_CSV_fields:scalar:1:scalar\nfunc:Text_CSV_string:str:1:scalar\nfunc:Text_CSV__strip_eol:str:1:str\nfunc:Text_CSV__set_error:void:2:scalar,str\nfunc:Text_CSV__clear_buffer:void:1:scalar\nfunc:Text_CSV_parse:int:2:scalar,str\nfunc:Text_CSV_getline:scalar:2:scalar,scalar\nfunc:Text_CSV__escape_field:str:3:str,str,str\nfunc:Text_CSV_combine:int:2:scalar,scalar\n";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}
