/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

void test(void);
int main(int _argc, char **_argv);

void test(void) {
if (setjmp(*STRADA_TRY_PUSH()) == 0) {
    strada_throw_value(strada_new_str("error message"));
    STRADA_TRY_POP();
} else {
    STRADA_TRY_POP();
    StradaValue *__strada_exc = strada_get_exception();
    {
        StradaValue *e = __strada_exc;
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Caught: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, e); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        strada_decref(e);
    }
}
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

{
    StradaValue *i = strada_new_int(0);
    for (; (strada_to_num(i) < 100.0); ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; })) {
        test();
    }
    strada_decref(i);
}
return 0;
}


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:test:void:0::-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
