/* Generated by Strada Self-Hosting Compiler */
/* Package: main */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

StradaValue* MyError_new(StradaValue* msg);
StradaValue* OtherError_new(StradaValue* msg);
void test_catch(void);
void test_rethrow(void);
int main(int _argc, char **_argv);


/* OOP method registration forward declarations */
void __MyError_oop_init(void);
void __OtherError_oop_init(void);
StradaValue* MyError_new(StradaValue* msg) {
strada_incref(msg);
StradaValue *self = strada_new_hash();
strada_hash_set(strada_deref_hash(self), "message", msg);
{ StradaValue *__retval = strada_bless(strada_new_ref(self, '%'), "MyError");
    strada_decref(self);
    strada_decref(msg);
    return __retval; }
strada_decref(self);
}


StradaValue* OtherError_new(StradaValue* msg) {
strada_incref(msg);
StradaValue *self = strada_new_hash();
strada_hash_set(strada_deref_hash(self), "message", msg);
{ StradaValue *__retval = strada_bless(strada_new_ref(self, '%'), "OtherError");
    strada_decref(self);
    strada_decref(msg);
    return __retval; }
strada_decref(self);
}


void test_catch(void) {
if (setjmp(*STRADA_TRY_PUSH()) == 0) {
    strada_throw_value(({ StradaValue *__arg0 = strada_new_str("test error"); StradaValue *__call_result = MyError_new(__arg0); strada_decref(__arg0); __call_result; }));
    STRADA_TRY_POP();
} else {
    STRADA_TRY_POP();
    StradaValue *__strada_exc = strada_get_exception();
    if (strada_isa(__strada_exc, "MyError")) {
        StradaValue *e = __strada_exc;
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Caught MyError: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_hash_get(strada_deref_hash(e), "message")); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        strada_decref(e);
    } else {
        StradaValue *e = __strada_exc;
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Caught other: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, e); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        strada_decref(e);
    }
}
}


void test_rethrow(void) {
if (setjmp(*STRADA_TRY_PUSH()) == 0) {
    if (setjmp(*STRADA_TRY_PUSH()) == 0) {
        strada_throw_value(({ StradaValue *__arg0 = strada_new_str("other error"); StradaValue *__call_result = OtherError_new(__arg0); strada_decref(__arg0); __call_result; }));
        STRADA_TRY_POP();
    } else {
        STRADA_TRY_POP();
        StradaValue *__strada_exc = strada_get_exception();
        if (strada_isa(__strada_exc, "MyError")) {
            StradaValue *e = __strada_exc;
            ({ StradaValue *__say_tmp = strada_new_str("Should not reach here"); strada_say(__say_tmp); strada_decref(__say_tmp); });
            strada_decref(e);
        } else {
            strada_throw_value(__strada_exc);
        }
    }
    STRADA_TRY_POP();
} else {
    STRADA_TRY_POP();
    StradaValue *__strada_exc = strada_get_exception();
    if (strada_isa(__strada_exc, "OtherError")) {
        StradaValue *e = __strada_exc;
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("Caught rethrown OtherError: "); StradaValue *__concat_res = strada_concat_sv(__concat_l, strada_hash_get(strada_deref_hash(e), "message")); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        strada_decref(e);
    } else {
        strada_throw_value(__strada_exc);
    }
}
}


int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    /* Set package from file-level declaration */
    strada_set_package("main");

    /* Initialize OOP method registration */
    __MyError_oop_init();
    __OtherError_oop_init();

{
    StradaValue *i = strada_new_int(0);
    for (; (strada_to_num(i) < 100.0); ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; })) {
        test_catch();
        test_rethrow();
    }
    strada_decref(i);
}
return 0;
}


/* OOP method dispatch helper */
static StradaValue* __strada_get_arg(StradaValue* args, int idx) {
    if (!args || args->type != STRADA_ARRAY) return NULL;
    if ((size_t)idx >= args->value.av->size) return NULL;
    return args->value.av->elements[idx];
}

/* OOP method wrappers for package MyError */
static StradaValue* __wrap_MyError_new(StradaValue* self, StradaValue* args) {
    (void)args;
    return MyError_new(self);
}

/* OOP method registration initializer */
static int __MyError_oop_initialized = 0;
void __MyError_oop_init(void) {
    if (__MyError_oop_initialized) return;
    __MyError_oop_initialized = 1;

    strada_method_register("MyError", "new", __wrap_MyError_new);
}

/* OOP method wrappers for package OtherError */
static StradaValue* __wrap_OtherError_new(StradaValue* self, StradaValue* args) {
    (void)args;
    return OtherError_new(self);
}

/* OOP method registration initializer */
static int __OtherError_oop_initialized = 0;
void __OtherError_oop_init(void) {
    if (__OtherError_oop_initialized) return;
    __OtherError_oop_initialized = 1;

    strada_method_register("OtherError", "new", __wrap_OtherError_new);
}

/* Qualified name aliases for package main */
StradaValue* main__MyError_new(StradaValue* msg) { return MyError_new(msg); }
StradaValue* main__OtherError_new(StradaValue* msg) { return OtherError_new(msg); }
void main__test_catch(void) { return test_catch(); }
void main__test_rethrow(void) { return test_rethrow(); }


/* Strada export metadata for import_lib */
static const char* __strada_export_info(void) {
    return "func:MyError_new:scalar:1:str:-1\nfunc:OtherError_new:scalar:1:str:-1\nfunc:test_catch:void:0::-1\nfunc:test_rethrow:void:0::-1\n";
}

/* Strada module version */
static const char* __strada_version(void) {
    return "";
}
