/*
 This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 Copyright (c) 2026 Michael J. Flickinger
 
 This program is free software: you can redistribute it and/or modify  
 it under the terms of the GNU General Public License as published by  
 the Free Software Foundation, version 2.

 This program is distributed in the hope that it will be useful, but 
 WITHOUT ANY WARRANTY; without even the implied warranty of 
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 General Public License for more details.

 You should have received a copy of the GNU General Public License 
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;

StradaValue* starts_with(StradaValue* path, StradaValue* prefix);
StradaValue* get_path_info(StradaValue* path, StradaValue* prefix);
StradaValue* match_user_id(StradaValue* path);
StradaValue* strada_dispatch(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* body);

StradaValue* starts_with(StradaValue* path, StradaValue* prefix) {
    StradaValue *prefix_len = strada_new_int(strada_length(strada_to_str(prefix)));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(path)))) < strada_to_num(prefix_len)))) {
        return strada_new_int(0);
    }
    return strada_new_int(strcmp(strada_to_str(strada_substr(path, strada_to_int(strada_new_int(0)), strada_to_int(prefix_len))), strada_to_str(prefix)) == 0);
}

StradaValue* get_path_info(StradaValue* path, StradaValue* prefix) {
    StradaValue *prefix_len = strada_new_int(strada_length(strada_to_str(prefix)));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(path)))) <= strada_to_num(prefix_len)))) {
        return strada_new_str("");
    }
    return strada_substr(path, strada_to_int(prefix_len), strada_to_int(strada_new_num(strada_to_num(strada_new_int(strada_length(strada_to_str(path)))) - strada_to_num(prefix_len))));
}

StradaValue* match_user_id(StradaValue* path) {
    if (strada_to_bool(strada_new_int(!strada_to_bool(starts_with(path, strada_new_str("/user/")))))) {
        return strada_new_str("");
    }
    StradaValue *remainder = get_path_info(path, strada_new_str("/user/"));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(remainder)))) == strada_to_num(strada_new_int(0))))) {
        return strada_new_str("");
    }
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_new_int(strada_length(strada_to_str(remainder))))))) {
        StradaValue *ch = strada_substr(remainder, strada_to_int(i), strada_to_int(strada_new_int(1)));
        if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("0"))) < 0)) || strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("9"))) > 0))))) {
            return strada_new_str("");
        }
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    return remainder;
}

StradaValue* strada_dispatch(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* body) {
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/"))) == 0))))) {
        StradaValue *html = strada_new_str("<!DOCTYPE html>\n");
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<html><head><title>My Strada App</title>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<style>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("body { font-family: sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("h1 { color: #333; }\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("a { color: #0066cc; }\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str(".route { margin: 10px 0; }\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("</style></head>\n<body>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<h1>Welcome to My Strada App!</h1>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<p>This handler library is written entirely in Strada.</p>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<h2>Routes:</h2>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<ul>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/hello\">/hello</a> - Simple text response</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/api/status\">/api/status</a> - JSON status</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/user/42\">/user/{id}</a> - User by ID</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/api/users/123/profile\">/api/users/...</a> - Prefix match with path_info</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/files/docs/readme.txt\">/files/...</a> - File path</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<li class=\"route\"><a href=\"/echo?msg=Hello\">/echo?msg=...</a> - Query echo</li>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("</ul>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<h2>POST Routes:</h2>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("<p>POST /api/echo - Echoes request body as JSON</p>\n"))));
        html = strada_new_str_take(strada_concat(strada_to_str(html), strada_to_str(strada_new_str("</body></html>\n"))));
        return html;
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/hello"))) == 0))))) {
        return strada_new_str("Hello from the Strada library!");
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/api/status"))) == 0))))) {
        return strada_new_str("{\"status\":\"ok\",\"language\":\"Strada\",\"features\":[\"prefix-match\",\"path-info\"]}");
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0))) {
        StradaValue *user_id = match_user_id(path);
        if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(user_id)))) > strada_to_num(strada_new_int(0))))) {
            return strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("{\"user_id\":\"")), strada_to_str(user_id)))), strada_to_str(strada_new_str("\",\"name\":\"User "))))), strada_to_str(user_id)))), strada_to_str(strada_new_str("\"}"))));
        }
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0)) && strada_to_bool(starts_with(path, strada_new_str("/api/users")))))) {
        StradaValue *remainder = get_path_info(path, strada_new_str("/api/users"));
        return strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("{\"route\":\"/api/users\",\"path_info\":\"")), strada_to_str(remainder)))), strada_to_str(strada_new_str("\",\"method\":\""))))), strada_to_str(method)))), strada_to_str(strada_new_str("\"}"))));
    }
    if (strada_to_bool(starts_with(path, strada_new_str("/files/")))) {
        StradaValue *file_path = get_path_info(path, strada_new_str("/files"));
        return strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("File requested: ")), strada_to_str(file_path)))), strada_to_str(strada_new_str("\n(In a real app, this would serve the file)"))));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("GET"))) == 0)) && strada_to_bool(starts_with(path, strada_new_str("/echo")))))) {
        StradaValue *qpos = strada_new_int(strada_index(strada_to_str(path), strada_to_str(strada_new_str("?"))));
        if (strada_to_bool(strada_new_int(strada_to_num(qpos) > strada_to_num(strada_new_int(0))))) {
            StradaValue *query = strada_substr(path, strada_to_int(strada_new_num(strada_to_num(qpos) + strada_to_num(strada_new_int(1)))), strada_to_int(strada_new_num(strada_to_num(strada_new_num(strada_to_num(strada_new_int(strada_length(strada_to_str(path)))) - strada_to_num(qpos))) - strada_to_num(strada_new_int(1)))));
            StradaValue *msg_pos = strada_new_int(strada_index(strada_to_str(query), strada_to_str(strada_new_str("msg="))));
            if (strada_to_bool(strada_new_int(strada_to_num(msg_pos) >= strada_to_num(strada_new_int(0))))) {
                StradaValue *msg_value = strada_substr(query, strada_to_int(strada_new_num(strada_to_num(msg_pos) + strada_to_num(strada_new_int(4)))), strada_to_int(strada_new_num(strada_to_num(strada_new_num(strada_to_num(strada_new_int(strada_length(strada_to_str(query)))) - strada_to_num(msg_pos))) - strada_to_num(strada_new_int(4)))));
                StradaValue *amp_pos = strada_new_int(strada_index(strada_to_str(msg_value), strada_to_str(strada_new_str("&"))));
                if (strada_to_bool(strada_new_int(strada_to_num(amp_pos) > strada_to_num(strada_new_int(0))))) {
                    msg_value = strada_substr(msg_value, strada_to_int(strada_new_int(0)), strada_to_int(amp_pos));
                }
                return strada_new_str_take(strada_concat(strada_to_str(strada_new_str("Echo: ")), strada_to_str(msg_value)));
            }
        }
        return strada_new_str("Echo: (no message provided)");
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("POST"))) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/api/echo"))) == 0))))) {
        return strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("{\"received\":true,\"body_length\":")), strada_to_str(strada_new_int(strada_length(strada_to_str(body))))))), strada_to_str(strada_new_str(",\"body\":\""))))), strada_to_str(body)))), strada_to_str(strada_new_str("\"}"))));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(method), strada_to_str(strada_new_str("POST"))) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/api/data"))) == 0))))) {
        return strada_new_str_take(strada_concat(strada_to_str(strada_new_str_take(strada_concat(strada_to_str(strada_new_str("STATUS:201:Created - received ")), strada_to_str(strada_new_int(strada_length(strada_to_str(body))))))), strada_to_str(strada_new_str(" bytes"))));
    }
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(path), strada_to_str(strada_new_str("/old-page"))) == 0))) {
        return strada_new_str("REDIRECT:/");
    }
    return strada_new_str("");
}

