#!/usr/bin/perl
use strict;
use warnings;
use Unicode::Normalize qw(NFC);

my $unicore = "/usr/share/perl/5.38/unicore";

# Parse Decomposition.pl
my %canon_decomp;   # cp => [a, b] (canonical-only, 2-char form)
my %canon_decomp_n; # cp => [a, b, ...] for any-length canonical decomp
my %compat_decomp;  # cp => [a, b, ...]

open my $df, "<", "$unicore/Decomposition.pl" or die;
my $in_data = 0;
while (my $line = <$df>) {
    if ($line =~ /^return <</) { $in_data = 1; next; }
    next unless $in_data;
    last if $line =~ /^END/;
    next if $line =~ /^\s*$/;
    next if $line =~ /^\s*#/;
    # Format: "CP\t\tDECOMP" (single, two tabs) OR
    #         "START\tEND\tDECOMP" (range, single tab between hex pair).
    # Disambiguate via the tab pattern after the first hex.
    my ($start_hex, $end_hex, $tag, $rest);
    if ($line =~ /^([0-9A-F]+)\t\t(?:(<[^>]+>)\s+)?(.+?)$/) {
        ($start_hex, $end_hex, $tag, $rest) = ($1, $1, $2, $3);
    } elsif ($line =~ /^([0-9A-F]+)\t([0-9A-F]+)\t(?:(<[^>]+>)\s+)?(.+?)$/) {
        ($start_hex, $end_hex, $tag, $rest) = ($1, $2, $3, $4);
    } else { next; }
    my $start = hex $start_hex;
    my $end = hex $end_hex;
    my @parts = map { hex $_ } split /\s+/, $rest;
    for my $cp ($start .. $end) {
        if (defined $tag) {
            $compat_decomp{$cp} = [@parts];
        } else {
            $canon_decomp_n{$cp} = [@parts];
            if (@parts == 2) {
                $canon_decomp{$cp} = [@parts];
            }
        }
    }
}
close $df;

# Parse CombiningClass.pl — produces ranges: "START\tEND?\tCLASS"
my @ccc_ranges;  # [start, end, class]
open my $cf, "<", "$unicore/CombiningClass.pl" or die;
$in_data = 0;
while (my $line = <$cf>) {
    if ($line =~ /^return <</) { $in_data = 1; next; }
    next unless $in_data;
    last if $line =~ /^END/;
    next if $line =~ /^\s*$/;
    if ($line =~ /^([0-9A-F]+)\s+([0-9A-F]+)\s+(\d+)\s*$/) {
        push @ccc_ranges, [hex $1, hex $2, $3];
    } elsif ($line =~ /^([0-9A-F]+)\s+(\d+)\s*$/) {
        push @ccc_ranges, [hex $1, hex $1, $2];
    }
}
close $cf;

# Composition exclusions: a canonical-decomp pair (A, B) → CP composes
# only if NFC("AB") == CP. Filter via Unicode::Normalize.
my @comp_entries;  # [a, b, cp]
for my $cp (sort { $a <=> $b } keys %canon_decomp) {
    my ($a, $b) = @{ $canon_decomp{$cp} };
    next if $a >= 0xAC00 && $a < 0xD7A4;     # Hangul, handled algorithmically
    next if $cp >= 0xAC00 && $cp < 0xD7A4;
    # First component must be a starter (ccc=0) for composition to apply.
    my $a_ccc = 0;
    for my $r (@ccc_ranges) {
        if ($a >= $r->[0] && $a <= $r->[1]) { $a_ccc = $r->[2]; last; }
    }
    next if $a_ccc != 0;
    my $combined = chr($a) . chr($b);
    my $nfc = NFC($combined);
    if (length($nfc) == 1 && ord($nfc) == $cp) {
        push @comp_entries, [$a, $b, $cp];
    }
}

# Emit C tables
print "/* Auto-generated by tools/gen_normtables.pl from Unicode 15.0.0.\n";
print " *   DO NOT EDIT — regenerate via the script if Unicode is updated. */\n\n";

# Canonical decomposition table (full, up to 4 components flattened).
# Format: { cp, count, [a, b, c, d] }
print "typedef struct { uint32_t cp; uint8_t n; uint32_t parts[4]; } StradaNormDecompFull;\n\n";

print "static const StradaNormDecompFull strada_norm_canon_full[] = {\n";
for my $cp (sort { $a <=> $b } keys %canon_decomp_n) {
    my @p = @{ $canon_decomp_n{$cp} };
    next if @p > 4;
    my $n = scalar @p;
    my @padded = (@p, (0) x (4 - @p));
    printf "    {0x%04X, %d, {0x%04X, 0x%04X, 0x%04X, 0x%04X}},\n",
           $cp, $n, @padded;
}
print "};\n";
print "#define STRADA_NORM_CANON_FULL_N (sizeof(strada_norm_canon_full)/sizeof(strada_norm_canon_full[0]))\n\n";

# Compatibility decomposition table
print "static const StradaNormDecompFull strada_norm_compat_full[] = {\n";
for my $cp (sort { $a <=> $b } keys %compat_decomp) {
    my @p = @{ $compat_decomp{$cp} };
    next if @p > 4;
    my $n = scalar @p;
    my @padded = (@p, (0) x (4 - @p));
    printf "    {0x%04X, %d, {0x%04X, 0x%04X, 0x%04X, 0x%04X}},\n",
           $cp, $n, @padded;
}
print "};\n";
print "#define STRADA_NORM_COMPAT_FULL_N (sizeof(strada_norm_compat_full)/sizeof(strada_norm_compat_full[0]))\n\n";

# Composition table (post-exclusion)
print "typedef struct { uint32_t a; uint32_t b; uint32_t cp; } StradaNormComp;\n\n";
print "static const StradaNormComp strada_norm_comp[] = {\n";
for my $e (sort { $a->[0] <=> $b->[0] || $a->[1] <=> $b->[1] } @comp_entries) {
    printf "    {0x%04X, 0x%04X, 0x%04X},\n", @$e;
}
print "};\n";
print "#define STRADA_NORM_COMP_N (sizeof(strada_norm_comp)/sizeof(strada_norm_comp[0]))\n\n";

# Combining class table
print "typedef struct { uint32_t start; uint32_t end; uint8_t cls; } StradaNormCcc;\n\n";
print "static const StradaNormCcc strada_norm_ccc[] = {\n";
for my $r (sort { $a->[0] <=> $b->[0] } @ccc_ranges) {
    next if $r->[2] == 0;
    printf "    {0x%04X, 0x%04X, %d},\n", @$r;
}
print "};\n";
print "#define STRADA_NORM_CCC_N (sizeof(strada_norm_ccc)/sizeof(strada_norm_ccc[0]))\n\n";

printf STDERR "Generated tables:\n  canonical decomp: %d\n  compat decomp: %d\n  composition: %d\n  ccc ranges: %d\n",
    scalar(keys %canon_decomp_n), scalar(keys %compat_decomp),
    scalar(@comp_entries), scalar(grep { $_->[2] != 0 } @ccc_ranges);
