/*
 This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 Copyright (c) 2026 Michael J. Flickinger
 
 This program is free software: you can redistribute it and/or modify  
 it under the terms of the GNU General Public License as published by  
 the Free Software Foundation, version 2.

 This program is distributed in the hope that it will be useful, but 
 WITHOUT ANY WARRANTY; without even the implied warranty of 
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 General Public License for more details.

 You should have received a copy of the GNU General Public License 
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

StradaValue* convert_line(StradaValue* line);
StradaValue* add_header(StradaValue* source_file);
StradaValue* convert_file(StradaValue* input_path, StradaValue* output_path);
int main(int _argc, char **_argv);

StradaValue* convert_line(StradaValue* line) {
    StradaValue *result = line;
    StradaValue *trimmed = line;
    trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "^\\s+", "", NULL));
    trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "\\s+$", "", NULL));
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(trimmed), strada_to_str(strada_new_str(""))) == 0)) || strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^#")))))))) {
        return result;
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^use\\s+strict")))))) {
        return strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("# ")), strada_to_str(trimmed)))), strada_to_str(strada_new_str("  # Not needed in Strada"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^use\\s+warnings")))))) {
        return strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("# ")), strada_to_str(trimmed)))), strada_to_str(strada_new_str("  # Not needed in Strada"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^use\\s+feature")))))) {
        return strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("# ")), strada_to_str(trimmed)))), strada_to_str(strada_new_str("  # Strada has these built-in"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^sub\\s+\\w+\\s*\\{")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bsub\\s+")), strada_to_str(strada_new_str("func ")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\s*\\{")), strada_to_str(strada_new_str("() void {")), NULL));
        return result;
    }
    result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("\\bsub\\s*\\{")), strada_to_str(strada_new_str("func() void {"))));
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+\\$"))))) && strada_to_bool(strada_new_int(!strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+(scalar|int|num|str)")))))))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+\\$")), strada_to_str(strada_new_str("my scalar $")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+@"))))) && strada_to_bool(strada_new_int(!strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+array\\s+@")))))))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+@")), strada_to_str(strada_new_str("my array @")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+%"))))) && strada_to_bool(strada_new_int(!strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+hash\\s+%")))))))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bmy\\s+%")), strada_to_str(strada_new_str("my hash %")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+\\$")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+\\$")), strada_to_str(strada_new_str("my scalar $")), NULL));
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # was 'our'"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+@")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+@")), strada_to_str(strada_new_str("my array @")), NULL));
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # was 'our'"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+%")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bour\\s+%")), strada_to_str(strada_new_str("my hash %")), NULL));
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # was 'our'"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bforeach\\s+my")))))) {
        result = strada_new_str(strada_concat(strada_to_str(strada_new_str("    # TODO: Convert to while loop: ")), strada_to_str(trimmed)));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bunless\\s*\\(")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bunless\\s*\\(")), strada_to_str(strada_new_str("if (!(")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\)\\s*\\{")), strada_to_str(strada_new_str(")) {")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\buntil\\s*\\(")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\buntil\\s*\\(")), strada_to_str(strada_new_str("while (!(")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\)\\s*\\{")), strada_to_str(strada_new_str(")) {")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bprint\\s+\""))))) && strada_to_bool(strada_new_int(!strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bprint\\s*\\(")))))))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bprint\\s+")), strada_to_str(strada_new_str("print(")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str(";$")), strada_to_str(strada_new_str(");")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bsay\\s+\""))))) && strada_to_bool(strada_new_int(!strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bsay\\s*\\(")))))))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bsay\\s+")), strada_to_str(strada_new_str("say(")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str(";$")), strada_to_str(strada_new_str(");")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("my\\s*\\([^)]+\\)\\s*=\\s*@_")))))) {
        result = strada_new_str(strada_concat(strada_to_str(strada_new_str("    # TODO: Move to function parameters: ")), strada_to_str(trimmed)));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bqw\\s*[\\(\\[/]")))))) {
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # TODO: convert qw() to (\"a\", \"b\", ...)"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bwantarray\\b")))))) {
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # TODO: wantarray not in Strada"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bcaller\\b")))))) {
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # TODO: caller not in Strada"))));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bbless\\b")))))) {
        result = strada_new_str(strada_concat(strada_to_str(result), strada_to_str(strada_new_str("  # TODO: convert to Strada class"))));
    }
    return result;
}

StradaValue* add_header(StradaValue* source_file) {
    StradaValue *header = strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("# Converted from Perl: ")), strada_to_str(source_file)))), strada_to_str(strada_new_str("\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("# Generated by perl2strada\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("# NOTE: Manual review and adjustments may be required\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("\n"))));
    return header;
}

StradaValue* convert_file(StradaValue* input_path, StradaValue* output_path) {
    StradaValue *content = strada_slurp(strada_to_str(input_path));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(content)))) == strada_to_num(strada_new_int(0))))) {
        strada_say(strada_new_str(strada_concat(strada_to_str(strada_new_str("Error: Cannot read or empty file: ")), strada_to_str(input_path))));
        return strada_new_int(1);
    }
    StradaValue *lines = (({ StradaValue *__sv = strada_new_array(); __sv->value.av = strada_regex_split(strada_to_str(content), strada_to_str(strada_new_str("\n"))); __sv; }));
    StradaValue *output = add_header(input_path);
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_new_int(strada_size(lines)))))) {
        StradaValue *ln = strada_array_get(lines->value.av, strada_to_int(i));
        StradaValue *converted = convert_line(ln);
        output = strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(output), strada_to_str(converted)))), strada_to_str(strada_new_str("\n"))));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    strada_spew(strada_to_str(output_path), strada_to_str(output));
    strada_say(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("Converted: ")), strada_to_str(input_path)))), strada_to_str(strada_new_str(" -> "))))), strada_to_str(output_path))));
    return strada_new_int(0);
}

int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    StradaValue* argc = ARGC;
    StradaValue* argv = ARGV;

if (strada_to_bool(strada_new_int(strada_to_num(argc) < strada_to_num(strada_new_int(2))))) {
    strada_say(strada_new_str("Usage: perl2strada input.pl [output.strada]"));
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("Converts Perl code to Strada code."));
    strada_say(strada_new_str("If output file is not specified, uses input.strada"));
    return 1;
}
StradaValue *input = strada_array_get(argv->value.av, strada_to_int(strada_new_int(1)));
StradaValue *output = strada_new_str("");
if (strada_to_bool(strada_new_int(strada_to_num(argc) >= strada_to_num(strada_new_int(3))))) {
    output = strada_array_get(argv->value.av, strada_to_int(strada_new_int(2)));
} else {
    output = input;
    output = strada_new_str(strada_regex_replace(strada_to_str(output), strada_to_str(strada_new_str("\\.pl$")), strada_to_str(strada_new_str(".strada")), NULL));
    output = strada_new_str(strada_regex_replace(strada_to_str(output), strada_to_str(strada_new_str("\\.pm$")), strada_to_str(strada_new_str(".strada")), NULL));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(output), strada_to_str(input)) == 0))) {
        output = strada_new_str(strada_concat(strada_to_str(input), strada_to_str(strada_new_str(".strada"))));
    }
}
return convert_file(input, output);
}

