/*
 This file is part of the Strada Language (https://github.com/mjflick/strada-lang).
 Copyright (c) 2026 Michael J. Flickinger
 
 This program is free software: you can redistribute it and/or modify  
 it under the terms of the GNU General Public License as published by  
 the Free Software Foundation, version 2.

 This program is distributed in the hope that it will be useful, but 
 WITHOUT ANY WARRANTY; without even the implied warranty of 
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 General Public License for more details.

 You should have received a copy of the GNU General Public License 
 along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* Global command-line argument variables */
StradaValue *ARGV = NULL;
StradaValue *ARGC = NULL;

StradaValue* convert_line(StradaValue* line);
StradaValue* add_header(StradaValue* source_file);
StradaValue* convert_file(StradaValue* input_path, StradaValue* output_path);
int main(int _argc, char **_argv);

StradaValue* convert_line(StradaValue* line) {
    StradaValue *result = line;
    StradaValue *trimmed = line;
    trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "^\\s+", "", NULL));
    trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "\\s+$", "", NULL));
    if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(trimmed), strada_to_str(strada_new_str(""))) == 0)) || strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^#")))))))) {
        return result;
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^class\\s+")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bclass\\s+")), strada_to_str(strada_new_str("package ")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\s+extends\\s+\\w+")), strada_to_str(strada_new_str("")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\s*\\{\\s*$")), strada_to_str(strada_new_str(";")), NULL));
        return result;
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^func\\s+")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("func ")), strada_to_str(strada_new_str("sub ")), NULL));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("int ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("num ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("str ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("scalar ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("bool ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("array ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("hash ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\)\\s+\\w+\\s*\\{")), strada_to_str(strada_new_str(") {")), NULL));
        return result;
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^method\\s+")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("method ")), strada_to_str(strada_new_str("sub ")), NULL));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("int ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("num ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("str ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("scalar ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("bool ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("array ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("hash ")), strada_to_str(strada_new_str(""))));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\)\\s+\\w+\\s*\\{")), strada_to_str(strada_new_str(") {")), NULL));
        return result;
    }
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my int ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my num ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my str ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my scalar ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my bool ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my array ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("my hash ")), strada_to_str(strada_new_str("my ")), NULL));
    result = strada_new_str(strada_replace_all(strada_to_str(result), strada_to_str(strada_new_str("\\bsize\\s*\\(\\s*@")), strada_to_str(strada_new_str("scalar(@"))));
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("\\bsize\\s*\\(\\s*%")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\bsize\\s*\\(\\s*%")), strada_to_str(strada_new_str("scalar(keys %")), NULL));
    }
    if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(result), strada_to_str(strada_new_str("^\\s*const\\s+")))))) {
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("const\\s+")), strada_to_str(strada_new_str("use constant ")), NULL));
        result = strada_new_str(strada_regex_replace(strada_to_str(result), strada_to_str(strada_new_str("\\s*=\\s*")), strada_to_str(strada_new_str(" => ")), NULL));
    }
    return result;
}

StradaValue* add_header(StradaValue* source_file) {
    StradaValue *header = strada_new_str("#!/usr/bin/env perl\n");
    header = strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("# Converted from Strada: "))))), strada_to_str(source_file)))), strada_to_str(strada_new_str("\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("# Generated by strada2perl\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("#\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("use strict;\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("use warnings;\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("use feature 'say';\n"))));
    header = strada_new_str(strada_concat(strada_to_str(header), strada_to_str(strada_new_str("\n"))));
    return header;
}

StradaValue* convert_file(StradaValue* input_path, StradaValue* output_path) {
    StradaValue *content = strada_slurp(strada_to_str(input_path));
    if (strada_to_bool(strada_new_int(strada_to_num(strada_new_int(strada_length(strada_to_str(content)))) == strada_to_num(strada_new_int(0))))) {
        strada_say(strada_new_str(strada_concat(strada_to_str(strada_new_str("Error: Cannot read or empty file: ")), strada_to_str(input_path))));
        return strada_new_int(1);
    }
    StradaValue *lines = (({ StradaValue *__sv = strada_new_array(); __sv->value.av = strada_regex_split(strada_to_str(content), strada_to_str(strada_new_str("\n"))); __sv; }));
    StradaValue *output = add_header(input_path);
    StradaValue *in_main = strada_new_int(0);
    StradaValue *brace_depth = strada_new_int(0);
    StradaValue *i = strada_new_int(0);
    while (strada_to_bool(strada_new_int(strada_to_num(i) < strada_to_num(strada_new_int(strada_size(lines)))))) {
        StradaValue *ln = strada_array_get(lines->value.av, strada_to_int(i));
        StradaValue *trimmed = ln;
        trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "^\\s+", "", NULL));
        trimmed = strada_new_str(strada_regex_replace(strada_to_str(trimmed), "\\s+$", "", NULL));
        if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^func\\s+main\\s*\\(")))))) {
            in_main = strada_new_int(1);
            brace_depth = strada_new_int(1);
            output = strada_new_str(strada_concat(strada_to_str(output), strada_to_str(strada_new_str("# Main\n"))));
            i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
            continue;
        }
        if (strada_to_bool(in_main)) {
            StradaValue *opens = strada_new_int(0);
            StradaValue *closes = strada_new_int(0);
            StradaValue *tmp = ln;
            while (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(tmp), strada_to_str(strada_new_str("\\{")))))) {
                opens = strada_new_num(strada_to_num(opens) + strada_to_num(strada_new_int(1)));
                tmp = strada_new_str(strada_regex_replace(strada_to_str(tmp), strada_to_str(strada_new_str("\\{")), strada_to_str(strada_new_str("")), NULL));
            }
            tmp = ln;
            while (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(tmp), strada_to_str(strada_new_str("\\}")))))) {
                closes = strada_new_num(strada_to_num(closes) + strada_to_num(strada_new_int(1)));
                tmp = strada_new_str(strada_regex_replace(strada_to_str(tmp), strada_to_str(strada_new_str("\\}")), strada_to_str(strada_new_str("")), NULL));
            }
            brace_depth = strada_new_num(strada_to_num(strada_new_num(strada_to_num(brace_depth) + strada_to_num(opens))) - strada_to_num(closes));
            if (strada_to_bool(strada_new_int(strada_to_bool(strada_new_int(strcmp(strada_to_str(trimmed), strada_to_str(strada_new_str("}"))) == 0)) && strada_to_bool(strada_new_int(strada_to_num(brace_depth) <= strada_to_num(strada_new_int(0))))))) {
                in_main = strada_new_int(0);
                i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
                continue;
            }
            if (strada_to_bool(strada_new_int(strada_regex_match(strada_to_str(trimmed), strada_to_str(strada_new_str("^return\\s+0\\s*;")))))) {
                i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
                continue;
            }
        }
        StradaValue *converted = convert_line(ln);
        output = strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(output), strada_to_str(converted)))), strada_to_str(strada_new_str("\n"))));
        i = strada_new_num(strada_to_num(i) + strada_to_num(strada_new_int(1)));
    }
    strada_spew(strada_to_str(output_path), strada_to_str(output));
    strada_say(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str(strada_concat(strada_to_str(strada_new_str("Converted: ")), strada_to_str(input_path)))), strada_to_str(strada_new_str(" -> "))))), strada_to_str(output_path))));
    return strada_new_int(0);
}

int main(int _argc, char **_argv) {
    /* Initialize proctitle support */
    strada_init_proctitle(_argc, _argv);

    /* Populate global ARGV array */
    ARGV = strada_new_array();
    for (int i = 0; i < _argc; i++) {
        strada_array_push(ARGV->value.av, strada_new_str(_argv[i]));
    }
    ARGC = strada_new_int(_argc);

    StradaValue* argc = ARGC;
    StradaValue* argv = ARGV;

if (strada_to_bool(strada_new_int(strada_to_num(argc) < strada_to_num(strada_new_int(2))))) {
    strada_say(strada_new_str("Usage: strada2perl input.strada [output.pl]"));
    strada_say(strada_new_str(""));
    strada_say(strada_new_str("Converts Strada code to Perl 5 code."));
    strada_say(strada_new_str("If output file is not specified, uses input.pl"));
    return 1;
}
StradaValue *input = strada_array_get(argv->value.av, strada_to_int(strada_new_int(1)));
StradaValue *output = strada_new_str("");
if (strada_to_bool(strada_new_int(strada_to_num(argc) >= strada_to_num(strada_new_int(3))))) {
    output = strada_array_get(argv->value.av, strada_to_int(strada_new_int(2)));
} else {
    output = input;
    output = strada_new_str(strada_regex_replace(strada_to_str(output), strada_to_str(strada_new_str("\\.strada$")), strada_to_str(strada_new_str(".pl")), NULL));
    if (strada_to_bool(strada_new_int(strcmp(strada_to_str(output), strada_to_str(input)) == 0))) {
        output = strada_new_str(strada_concat(strada_to_str(input), strada_to_str(strada_new_str(".pl"))));
    }
}
return convert_file(input, output);
}

